# Generated by Django 4.2.5 on 2026-01-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0096_paymentinvoice_archived_date_and_more"),
        ("organization", "0007_remove_userorganizationmembership_accepted"),
        ("program", "0007_set_uuid_unique"),
        ("flags", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flag",
            name="opportunities",
            field=models.ManyToManyField(
                blank=True, help_text="Activate this flag for these opportunities.", to="opportunity.opportunity"
            ),
        ),
        migrations.AddField(
            model_name="flag",
            name="organizations",
            field=models.ManyToManyField(
                blank=True, help_text="Activate this flag for these organizations.", to="organization.organization"
            ),
        ),
        migrations.AddField(
            model_name="flag",
            name="programs",
            field=models.ManyToManyField(
                blank=True, help_text="Activate this flag for these programs.", to="program.program"
            ),
        ),
    ]
