# Generated by Django 4.2.5 on 2026-02-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0008_lloentity_organization_llo_entity"),
        ("flags", "0002_flag_opportunities_flag_organizations_flag_programs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flag",
            name="organizations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Activate this flag for these workspaces.",
                to="organization.organization",
                verbose_name="Workspaces",
            ),
        ),
    ]
