# Generated by Django 4.2.5 on 2025-12-17 23:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminBoundary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "iso_code",
                    models.CharField(db_index=True, help_text="ISO 3166-1 alpha-3 country code", max_length=3),
                ),
                (
                    "admin_level",
                    models.PositiveSmallIntegerField(
                        db_index=True, help_text="Admin level (0=country, 1=state/province, 2=district, etc.)"
                    ),
                ),
                ("name", models.CharField(help_text="Name of the administrative unit", max_length=255)),
                (
                    "name_local",
                    models.CharField(blank=True, help_text="Local/native name if available", max_length=255),
                ),
                (
                    "boundary_id",
                    models.CharField(help_text="Unique ID from source (shapeID or OSM ID)", max_length=100, unique=True),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        help_text="Boundary polygon in WGS84", srid=4326
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("geoboundaries", "geoBoundaries"),
                            ("osm", "OpenStreetMap"),
                            ("grid3", "GRID3"),
                            ("hdx", "HDX (OCHA COD)"),
                            ("geopode", "GeoPoDe"),
                        ],
                        db_index=True,
                        default="geoboundaries",
                        help_text="Data source (geoBoundaries, OpenStreetMap, GRID3, HDX, or GeoPoDe)",
                        max_length=20,
                    ),
                ),
                ("source_url", models.URLField(blank=True, help_text="URL where boundary data was downloaded from")),
                (
                    "downloaded_at",
                    models.DateTimeField(auto_now_add=True, help_text="When this boundary was downloaded"),
                ),
            ],
            options={
                "verbose_name": "Admin boundary",
                "verbose_name_plural": "Admin boundaries",
                "db_table": "labs_admin_boundary",
                "ordering": ["iso_code", "admin_level", "name"],
                "indexes": [
                    models.Index(fields=["iso_code", "admin_level"], name="labs_admin__iso_cod_6d6750_idx"),
                    models.Index(fields=["source", "iso_code"], name="labs_admin__source_037f13_idx"),
                ],
            },
        ),
    ]
