# Generated by Django 4.2.5 on 2025-12-18 01:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_boundaries", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="adminboundary",
            new_name="labs_admin__iso_cod_6d6750_idx",
            old_name="solicitatio_iso_cod_9b229e_idx",
        ),
        migrations.AlterModelTable(
            name="adminboundary",
            table="labs_admin_boundary",
        ),
    ]
