# Generated by Django 4.2.5 on 2025-12-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_boundaries", "0002_rename_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminboundary",
            name="parent_name",
        ),
        migrations.AddField(
            model_name="adminboundary",
            name="source",
            field=models.CharField(
                choices=[("geoboundaries", "geoBoundaries"), ("osm", "OpenStreetMap")],
                db_index=True,
                default="geoboundaries",
                help_text="Data source (geoBoundaries or OpenStreetMap)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="adminboundary",
            name="boundary_id",
            field=models.CharField(help_text="Unique ID from source (shapeID or OSM ID)", max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name="adminboundary",
            index=models.Index(fields=["source", "iso_code"], name="labs_admin__source_037f13_idx"),
        ),
    ]
