# Generated by Django 4.2.5 on 2025-12-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_boundaries", "0004_add_grid3_hdx_sources"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminboundary",
            name="source",
            field=models.CharField(
                choices=[
                    ("geoboundaries", "geoBoundaries"),
                    ("osm", "OpenStreetMap"),
                    ("grid3", "GRID3"),
                    ("hdx", "HDX (OCHA COD)"),
                    ("geopode", "GeoPoDe"),
                ],
                db_index=True,
                default="geoboundaries",
                help_text="Data source (geoBoundaries, OpenStreetMap, GRID3, or HDX)",
                max_length=20,
            ),
        ),
    ]
