# Generated by Django 4.2.5 on 2025-08-16 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organization", "0006_organization_program_manager"),
        ("program", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Solicitation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_by", models.CharField(max_length=255)),
                ("modified_by", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(help_text="Rich text description of the program and requirements")),
                (
                    "target_population",
                    models.CharField(
                        help_text="Who will be served (e.g., 'Children under 5 in rural areas')", max_length=255
                    ),
                ),
                ("scope_of_work", models.TextField(help_text="What work needs to be done")),
                (
                    "solicitation_type",
                    models.CharField(
                        choices=[("eoi", "Expression of Interest"), ("rfp", "Request for Proposal")],
                        default="eoi",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "is_publicly_listed",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this appears in public listings (can still be accessed via direct URL if False)",
                    ),
                ),
                ("expected_start_date", models.DateField(blank=True, null=True)),
                ("expected_end_date", models.DateField(blank=True, null=True)),
                ("application_deadline", models.DateField()),
                (
                    "estimated_scale",
                    models.CharField(blank=True, help_text="e.g., '40,000 children, 25-50 FLWs'", max_length=255),
                ),
                (
                    "attachments",
                    models.FileField(
                        blank=True, help_text="Supporting documents", null=True, upload_to="solicitations/attachments/"
                    ),
                ),
                (
                    "parent_solicitation",
                    models.ForeignKey(
                        blank=True,
                        help_text="For RFPs that follow from EOIs",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_solicitations",
                        to="solicitations.solicitation",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        help_text="The program that owns this solicitation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitations",
                        to="program.program",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="SolicitationResponse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_by", models.CharField(max_length=255)),
                ("modified_by", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("submission_date", models.DateTimeField(auto_now_add=True)),
                ("responses", models.JSONField(help_text="Flexible storage for question/answer pairs")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("progressed_to_rfp", "Progressed to RFP"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("attachments", models.FileField(blank=True, null=True, upload_to="solicitations/responses/")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitation_responses",
                        to="organization.organization",
                    ),
                ),
                (
                    "progressed_to_solicitation",
                    models.ForeignKey(
                        blank=True,
                        help_text="If this EOI response was accepted and progressed to RFP",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parent_responses",
                        to="solicitations.solicitation",
                    ),
                ),
                (
                    "solicitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="solicitations.solicitation",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submission_date"],
            },
        ),
        migrations.CreateModel(
            name="SolicitationQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("text", "Short Text"),
                            ("textarea", "Long Text"),
                            ("number", "Number"),
                            ("file", "File Upload"),
                            ("multiple_choice", "Multiple Choice"),
                        ],
                        default="textarea",
                        max_length=15,
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                (
                    "options",
                    models.JSONField(
                        blank=True, help_text="For multiple choice questions, store options as JSON array", null=True
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "solicitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="solicitations.solicitation",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SolicitationReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score", models.PositiveIntegerField(blank=True, help_text="Numeric score (1-100)", null=True)),
                ("tags", models.CharField(blank=True, help_text="Comma-separated tags", max_length=255)),
                ("notes", models.TextField(blank=True)),
                (
                    "recommendation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accept", "Accept"),
                            ("reject", "Reject"),
                            ("needs_more_info", "Needs More Information"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("review_date", models.DateTimeField(auto_now_add=True)),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="solicitations.solicitationresponse",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitation_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-review_date"],
                "unique_together": {("response", "reviewer")},
            },
        ),
        migrations.AddIndex(
            model_name="solicitationresponse",
            index=models.Index(fields=["status", "submission_date"], name="solicitatio_status_443b8c_idx"),
        ),
        migrations.AddIndex(
            model_name="solicitationresponse",
            index=models.Index(fields=["solicitation", "status"], name="solicitatio_solicit_abe7fd_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="solicitationresponse",
            unique_together={("solicitation", "organization")},
        ),
        migrations.AlterUniqueTogether(
            name="solicitationquestion",
            unique_together={("solicitation", "order")},
        ),
        migrations.AddIndex(
            model_name="solicitation",
            index=models.Index(fields=["solicitation_type", "status"], name="solicitatio_solicit_4dd42c_idx"),
        ),
        migrations.AddIndex(
            model_name="solicitation",
            index=models.Index(fields=["is_publicly_listed", "status"], name="solicitatio_is_publ_36c4bd_idx"),
        ),
        migrations.AddIndex(
            model_name="solicitation",
            index=models.Index(fields=["application_deadline"], name="solicitatio_applica_08921a_idx"),
        ),
    ]
