# Generated by Django 4.2.5 on 2025-08-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solicitations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitationresponse",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("under_review", "Under Review"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("progressed_to_rfp", "Progressed to RFP"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
