# Generated by Django 4.2.5 on 2025-08-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solicitations", "0002_alter_solicitationresponse_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitationresponse",
            name="responses",
            field=models.JSONField(default=dict, help_text="Flexible storage for question/answer pairs"),
        ),
    ]
