# Generated by Django 4.2.5 on 2025-08-16 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("solicitations", "0003_alter_solicitationresponse_responses"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResponseAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_by", models.CharField(max_length=255)),
                ("modified_by", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(help_text="Supporting document", upload_to="solicitations/response_attachments/"),
                ),
                ("original_filename", models.CharField(help_text="Original filename when uploaded", max_length=255)),
                ("file_size", models.PositiveIntegerField(help_text="File size in bytes")),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_attachments",
                        to="solicitations.solicitationresponse",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
    ]
