# Generated by Django 4.2.5 on 2025-08-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solicitations", "0004_add_response_attachment_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solicitationresponse",
            name="attachments",
        ),
        migrations.AlterField(
            model_name="solicitation",
            name="application_deadline",
            field=models.DateField(verbose_name="Application Deadline"),
        ),
        migrations.AlterField(
            model_name="solicitation",
            name="description",
            field=models.TextField(
                help_text="Rich text description of the program and requirements", verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="solicitation",
            name="expected_end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Expected End Date"),
        ),
        migrations.AlterField(
            model_name="solicitation",
            name="expected_start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Expected Start Date"),
        ),
        migrations.AlterField(
            model_name="solicitation",
            name="is_publicly_listed",
            field=models.BooleanField(
                default=True,
                help_text="Whether this appears in public listings (can still be accessed via direct URL if False)",
                verbose_name="Publicly Listed",
            ),
        ),
        migrations.AlterField(
            model_name="solicitation",
            name="solicitation_type",
            field=models.CharField(
                choices=[("eoi", "Expression of Interest"), ("rfp", "Request for Proposal")],
                default="eoi",
                max_length=3,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="solicitation",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("active", "Active"), ("completed", "Completed"), ("closed", "Closed")],
                default="draft",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="solicitation",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Solicitation Title"),
        ),
        migrations.AlterField(
            model_name="solicitationreview",
            name="recommendation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("recommended", "Recommended"),
                    ("not_recommended", "Not Recommended"),
                    ("neutral", "Neutral"),
                ],
                max_length=15,
                null=True,
            ),
        ),
    ]
