# Generated by Django 4.2.5 on 2025-08-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solicitations", "0005_remove_solicitationresponse_attachments_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solicitation",
            name="parent_solicitation",
        ),
        migrations.RemoveField(
            model_name="solicitationresponse",
            name="progressed_to_solicitation",
        ),
        migrations.AlterField(
            model_name="solicitationresponse",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("under_review", "Under Review"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
