# Generated by Django 4.2.5 on 2025-08-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solicitations", "0006_remove_eoi_rfp_relationships"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitation",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("active", "Active"), ("closed", "Closed")],
                default="draft",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
