# Generated by Django 4.2.5 on 2025-08-21 20:43

from django.db import migrations, models


def convert_old_statuses(apps, schema_editor):
    """Convert old statuses to new simplified statuses"""
    SolicitationResponse = apps.get_model('solicitations', 'SolicitationResponse')
    
    # Convert all non-draft statuses to 'submitted'
    old_statuses = ['under_review', 'accepted', 'rejected']
    for old_status in old_statuses:
        SolicitationResponse.objects.filter(status=old_status).update(status='submitted')


def reverse_convert_old_statuses(apps, schema_editor):
    """Reverse migration - not possible to restore original statuses"""
    # We can't restore the original statuses since we don't know what they were
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("solicitations", "0007_remove_completed_status"),
    ]

    operations = [
        # First convert the data
        migrations.RunPython(convert_old_statuses, reverse_convert_old_statuses, hints={'run_on_secondary': False}),
        # Then alter the field
        migrations.AlterField(
            model_name="solicitationresponse",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("submitted", "Submitted")], default="draft", max_length=20
            ),
        ),
    ]
