# Generated by Django 4.2.5 on 2025-10-24 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0083_add_question_id_to_blobmeta"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpportunityBotConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_by", models.CharField(max_length=255)),
                ("modified_by", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("ocs_bot_id", models.CharField(help_text="OCS Bot ID for this opportunity", max_length=255)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether AI assistant is enabled for this opportunity"
                    ),
                ),
                (
                    "bot_name",
                    models.CharField(blank=True, help_text="Human-readable bot name for UI display", max_length=255),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional bot configuration (channel preferences, prompts, etc.)",
                    ),
                ),
                (
                    "opportunity",
                    models.OneToOneField(
                        help_text="The opportunity this bot configuration is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_configuration",
                        to="opportunity.opportunity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opportunity Bot Configuration",
                "verbose_name_plural": "Opportunity Bot Configurations",
            },
        ),
    ]
