# Generated by Django 4.2.5 on 2025-10-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_add_opportunity_bot_configuration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskaisession",
            name="ocs_session_id",
            field=models.CharField(
                blank=True, help_text="Session ID from OCS API", max_length=255, null=True, unique=True
            ),
        ),
    ]
