# Generated by Django 4.2.5 on 2025-10-29 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_alter_taskaisession_ocs_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskevent",
            name="ai_session",
            field=models.ForeignKey(
                blank=True,
                help_text="AI session associated with this event (for AI conversation events)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="tasks.taskaisession",
            ),
        ),
    ]
