# Generated by Django 4.2.5 on 2025-11-11 02:45

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("labs", "0003_change_organization_id_to_charfield"),
        ("tasks", "0005_remove_old_orm_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskRecord",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("labs.experimentrecord",),
        ),
    ]
