# Generated by Django 4.2.5 on 2024-07-31 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("opportunity", "0053_assessment_opportunity_access_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_by", models.CharField(max_length=255)),
                ("modified_by", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.CharField()),
                (
                    "delivery_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="opportunity.deliverytype"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
