# Generated by Django 4.2.5 on 2025-11-05 16:17

from django.db import migrations


def update_delivery_type(apps, schema_editor):
    Program = apps.get_model('program', 'Program')
    ManagedOpportunity = apps.get_model('program', 'ManagedOpportunity')

    for program in Program.objects.all():
        ManagedOpportunity.objects.filter(
            program=program
        ).update(delivery_type=program.delivery_type)



class Migration(migrations.Migration):
    dependencies = [
        ("program", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(update_delivery_type,  migrations.RunPython.noop,
            hints={"run_on_secondary": False}),  
    ]