# Generated by Django 4.2.5 on 2025-11-05 16:17

from django.db import migrations
from django.db.models import F, Subquery, OuterRef


def update_delivery_type(apps, schema_editor):
    Program = apps.get_model('program', 'Program')
    ManagedOpportunity = apps.get_model('program', 'ManagedOpportunity')

    for program in Program.objects.all():
        opps = ManagedOpportunity.objects.filter(program=program)

        for opp in opps:
            opp.delivery_type = program.delivery_type
            opp.save(update_fields=['delivery_type'])



class Migration(migrations.Migration):
    dependencies = [
        ("program", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(update_delivery_type,  migrations.RunPython.noop,
            hints={"run_on_secondary": False}),  
    ]