# Generated by Django 4.2.5 on 2024-08-08 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0054_opportunity_managed_alter_opportunity_organization"),
        ("program", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagedOpportunity",
            fields=[
                (
                    "opportunity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="opportunity.opportunity",
                    ),
                ),
                ("claimed", models.BooleanField(default=False)),
                ("org_pay_per_visit", models.IntegerField(null=True)),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="program.program")),
            ],
            options={
                "abstract": False,
            },
            bases=("opportunity.opportunity",),
        ),
    ]
