# Generated by Django 4.2.5 on 2024-08-13 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0007_remove_userorganizationmembership_program_manager_and_more"),
        ("program", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagedOpportunityApplication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_by", models.CharField(max_length=255)),
                ("modified_by", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("applied", "Applied"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="invited",
                        max_length=20,
                    ),
                ),
                (
                    "managed_opportunity",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="program.managedopportunity"),
                ),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organization.organization"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
