# Generated by Django 4.2.5 on 2025-12-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0002_update_delivery_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="budget",
            field=models.PositiveBigIntegerField(),
        ),
    ]
