# Generated by Django 4.2.5 on 2025-11-11 02:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0002_alter_program_description"),
        ("program", "0002_update_delivery_type"),
    ]

    operations = []
