# Generated by Django 4.2.5 on 2025-11-11 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0084_currency_country_opportunity_currency_fk"),
        ("program", "0002_update_delivery_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="currency_fk",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="opportunity.currency"
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="country",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="opportunity.country"
            ),
        ),
    ]
