# Generated by Django 4.2.5 on 2025-11-11 09:40

import django.db.models.deletion
from django.db import migrations, models

from commcare_connect.program.utils import populate_currency_and_country_fk_for_model


def populate_program_currency_and_country_fk(apps, schema_editor):
    populate_currency_and_country_fk_for_model(apps, "Program", "program", "program")


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0084_currency_country_opportunity_currency_fk"),
        ("program", "0002_update_delivery_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="currency_fk",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="opportunity.currency"
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="country",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="opportunity.country"
            ),
        ),
        migrations.RunPython(
            populate_program_currency_and_country_fk,
            reverse_code=migrations.RunPython.noop,
            hints={"run_on_secondary": False},
        ),
    ]
