# Generated by Django 4.2.5 on 2026-01-02 11:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0005_remove_program_currency"),
        ("opportunity", "0094_remove_opportunity_currency_fk_opportunity_currency"),
    ]

    operations = [
        migrations.RenameField(
            model_name="program",
            old_name="currency_fk",
            new_name="currency",
        ),
    ]
