# Generated by Django 4.2.5 on 2026-01-01 07:52

from django.db import migrations


def gen_uuid(apps, schema_editor):
    connection = schema_editor.connection

    def backfill_uuid(table_name, field_name):
        """
        Bulk update NULL UUIDs in a given table.
        Uses PostgreSQL gen_random_uuid() function.
        """
        with connection.cursor() as cursor:
            cursor.execute(f"""
                UPDATE {table_name}
                SET {field_name} = gen_random_uuid()
                WHERE {field_name} IS NULL;
            """)

    backfill_uuid("program_program", "program_id")
    backfill_uuid("program_programapplication", "program_application_id")


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0005_program_program_id_and_more"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop, hints={"run_on_secondary": False}),
    ]
