# Generated by Django 4.2.5 on 2026-01-02 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0006_backfill_uuid_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="currency",
        ),
    ]
