# Generated by Django 4.2.17 on 2025-01-16 14:03

from django.db import migrations
from django_celery_beat.models import PeriodicTask, CrontabSchedule


def create_monthly_delivery_reminder_periodic_task(apps, schema_editor):
    # Create a schedule for the 25th of every month at 9:00 AM UTC
    schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="0",
        hour="9",
        day_of_week="*",
        day_of_month="25",
        month_of_year="*",
    )
    PeriodicTask.objects.update_or_create(
        crontab=schedule,
        name="send_monthly_delivery_reminder",
        task="commcare_connect.program.tasks.send_monthly_delivery_reminder_email",
    )


def delete_monthly_delivery_reminder_periodic_task(apps, schema_editor):
    PeriodicTask.objects.filter(
        name="send_monthly_delivery_reminder",
        task="commcare_connect.program.tasks.send_monthly_delivery_reminder_email",
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0006_backfill_uuid_fields"),
    ]

    operations = [
        migrations.RunPython(
            create_monthly_delivery_reminder_periodic_task, 
            delete_monthly_delivery_reminder_periodic_task,
            hints={"run_on_secondary": False}
        )
    ]
