# Generated by Django 4.2.5 on 2026-01-01 07:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0006_backfill_uuid_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="program_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="programapplication",
            name="program_application_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
