# Generated by Django 4.2.5 on 2026-01-19 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0007_remove_program_currency"),
        ("opportunity", "0098_paymentunit_org_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="managedopportunity",
            name="org_pay_per_visit",
        ),
    ]
