# Generated by Django 4.2.5 on 2026-01-19 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0010_alter_program_program_id_and_more"),
        ("opportunity", "0105_paymentunit_org_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="managedopportunity",
            name="org_pay_per_visit",
        ),
    ]
