# Generated by Django 4.2.3 on 2023-08-10 15:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={},
        ),
        migrations.AlterModelOptions(
            name="userorganizationmembership",
            options={},
        ),
    ]
