# Generated by Django 4.2.5 on 2023-09-25 07:10

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organization", "0003_organization_members_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userorganizationmembership",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userorganizationmembership",
            name="invite_id",
            field=models.CharField(default=uuid.uuid4, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="userorganizationmembership",
            unique_together={("user", "organization")},
        ),
        migrations.AddIndex(
            model_name="userorganizationmembership",
            index=models.Index(fields=["invite_id"], name="organizatio_invite__0504c3_idx"),
        ),
    ]
