# Generated by Django 4.2.5 on 2024-08-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0005_alter_userorganizationmembership_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="userorganizationmembership",
            name="program_manager",
            field=models.BooleanField(default=False),
        ),
    ]
