# Generated by Django 4.2.5 on 2025-10-07 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0006_organization_program_manager"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userorganizationmembership",
            name="accepted",
        ),
    ]
