# Generated by Django 4.2.5 on 2026-02-02 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0007_remove_userorganizationmembership_accepted"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLOEntity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="organization",
            name="llo_entity",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="organization.lloentity"
            ),
        ),
    ]
