# Generated by Django 4.2.5 on 2026-02-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0008_lloentity_organization_llo_entity"),
    ]

    operations = [
        migrations.AddField(
            model_name="lloentity",
            name="short_name",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
