# Generated by Django 4.2.3 on 2023-07-26 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_userorganizationmembership_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="members",
            field=models.ManyToManyField(
                related_name="organizations", through="users.UserOrganizationMembership", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
