# Generated by Django 4.2.3 on 2023-07-31 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_organization_members"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectUser",
            fields=[
                ("created_by", models.CharField(max_length=255)),
                ("modified_by", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="connect_user",
                        related_query_name="connect_user",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("remote_id", models.IntegerField()),
                ("phone", models.CharField(max_length=25)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
