# Generated by Django 4.2.3 on 2023-08-10 15:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_organization_table_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="userorganizationmembership",
            options={"managed": False},
        ),
        migrations.RemoveField(
            model_name="userorganizationmembership",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="userorganizationmembership",
            name="user",
        ),
        migrations.DeleteModel(
            name="Organization",
        ),
        migrations.DeleteModel(
            name="UserOrganizationMembership",
        ),
    ]
