# Generated by Django 4.2.3 on 2023-08-15 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_user_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectIDUserLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("commcare_username", models.TextField()),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name="connectiduserlink",
            constraint=models.UniqueConstraint(fields=("user", "commcare_username"), name="connect_user"),
        ),
    ]
