# Generated by Django 4.2.3 on 2023-09-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_connectiduserlink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email address"),
        ),
    ]
