# Generated by Django 4.2.5 on 2025-03-10 06:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_connectiduserlink_domain"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"permissions": [("demo_users_access", "Allow viewing OTPs for demo users")]},
        ),
    ]
