# Generated by Django 4.2.5 on 2025-06-27 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ("users", "0011_connectiduserlink_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="HQServer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "oauth_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="connectiduserlink",
            name="hq_server",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="users.hqserver"),
        ),
    ]
