# Generated by Django 4.2.5 on 2025-07-10 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("commcarehq", "0001_initial"),
        ("users", "0011_connectiduserlink_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectiduserlink",
            name="hq_server",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="commcarehq.hqserver"
            ),
        ),
    ]
