# Generated by Django 4.2.5 on 2025-08-29 12:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("demo_users_access", "Allow viewing OTPs for demo users"),
                    ("otp_access", "Allow fetching OTPs for Connect users"),
                ]
            },
        ),
    ]
