# Generated by Django 4.2.5 on 2025-10-07 11:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("demo_users_access", "Allow viewing OTPs for demo users"),
                    ("otp_access", "Allow fetching OTPs for Connect users"),
                    ("kpi_report_access", "Allow access to KPI reports"),
                    ("all_org_access", "Allow admin access to all organizations"),
                ]
            },
        ),
    ]
