# Generated by Django 4.2.5 on 2025-10-09 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0083_credentialconfiguration"),
        ("users", "0013_alter_user_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCredential",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("issued_on", models.DateTimeField(blank=True, null=True)),
                (
                    "credential_type",
                    models.CharField(choices=[("LEARN", "Learn"), ("DELIVERY", "Deliver")], max_length=32),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("25_DELIVERIES", "25 Deliveries"),
                            ("50_DELIVERIES", "50 Deliveries"),
                            ("100_DELIVERIES", "100 Deliveries"),
                            ("200_DELIVERIES", "200 Deliveries"),
                            ("500_DELIVERIES", "500 Deliveries"),
                            ("1000_DELIVERIES", "1000 Deliveries"),
                            ("LEARN_PASSED", "Learning passed"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "delivery_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="opportunity.deliverytype"),
                ),
                (
                    "opportunity",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="opportunity.opportunity"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("user", "opportunity", "credential_type")},
            },
        ),
    ]
