# Generated by Django 4.2.5 on 2025-10-30 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0084_create_issue_credentials_periodic_task"),
        ("users", "0014_usercredential"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercredential",
            name="delivery_type",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="opportunity.deliverytype"
            ),
        ),
    ]
