# Generated by Django 4.2.5 on 2025-11-10 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0085_create_issue_credentials_periodic_task"),
        ("users", "0015_alter_user_options"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usercredential",
            unique_together={("user", "opportunity", "credential_type", "level")},
        ),
        migrations.AlterField(
            model_name="usercredential",
            name="delivery_type",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="opportunity.deliverytype"
            ),
        ),
    ]
