# Generated by Django 4.2.5 on 2025-11-24 08:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_alter_usercredential_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("demo_users_access", "Allow viewing OTPs for demo users"),
                    ("otp_access", "Allow fetching OTPs for Connect users"),
                    ("kpi_report_access", "Allow access to KPI reports"),
                    ("all_org_access", "Allow admin access to all organizations"),
                    ("view_commcarehq_form_link", "Can view CommCareHQ form link"),
                    ("org_management_settings_access", "Can manage organizations settings"),
                ]
            },
        ),
    ]
