# Generated by Django 4.2.5 on 2026-01-22 11:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
