# Generated by Django 4.2.5 on 2026-01-22 11:32

from django.db import migrations, models
import uuid


def gen_uuid(apps, schema_editor):
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        cursor.execute("""
            UPDATE users_user
            SET user_id = gen_random_uuid();
        """)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_user_user_id"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop, hints={"run_on_secondary": False}),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
