# Generated by Django 4.2.5 on 2026-02-19 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("demo_users_access", "Allow viewing OTPs for demo users"),
                    ("otp_access", "Allow fetching OTPs for Connect users"),
                    ("kpi_report_access", "Allow access to KPI reports"),
                    ("all_org_access", "Allow admin access to all organizations"),
                    ("view_commcarehq_form_link", "Can view CommCareHQ form link"),
                    ("org_management_settings_access", "Can manage organizations settings"),
                    ("workspace_entity_management_access", "Can manage LLO Entities for organizations"),
                    ("product_features_access", "Can access and manage product features (flags and switches)"),
                ]
            },
        ),
    ]
