# Generated by Django 4.2.5 on 2026-02-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectiduserlink",
            name="hq_case_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
