# Generated by Django 4.2.5 on 2026-05-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0025_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectiduserlink",
            name="hq_user_uuid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
