# Generated by Django 4.2.30 on 2026-06-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_connectiduserlink_hq_user_uuid"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="connectiduserlink",
            name="connect_user",
        ),
        migrations.AddConstraint(
            model_name="connectiduserlink",
            constraint=models.UniqueConstraint(
                fields=("user", "commcare_username", "hq_server"), name="connect_user"
            ),
        ),
    ]
