webservers:
  hosts:
    web0:
      ansible_host: i-0901d8af0c29c69cf
    web1:
      ansible_host: i-0a766713cb0d2fe96
    celery0:
      ansible_host: i-0816b5db3a153135e
  vars:
    secrets_file: 'Ansible Secrets - Production'
    commcare_hq_url: 'https://www.commcarehq.org'
    deploy_environment: 'production'
    env_file: 'connect.docker.env.j2'

connectid:
  hosts:
    connectid_web0:
      ansible_host: i-01d4755cad044dcae
    connectid_celery0:
      ansible_host: i-090b0c432298694c5
  vars:
    secrets_file: 'Ansible Secrets - Production'
    commcare_hq_url: 'https://www.commcarehq.org'
    deploy_environment: 'production'
    env_file: 'connectid.docker.env.j2'
    docker_env_file: '/home/connect/www/docker.env'
