from django.core.exceptions import FieldDoesNotExist

from commcare_connect.deid.config import STRATEGY_DROP_FIELD, AnonymizationConfig


def generate_anonymization_sql(anonymization_configs: list[AnonymizationConfig]) -> list[str]:
    """
    Generates SQL statements to anonymize the database based on the provided configurations.

    For each model and field specified in the configuration with a 'drop_field' strategy,
    this function creates an 'ALTER TABLE ... DROP COLUMN IF EXISTS ...;' statement.
    It uses Django's model metadata to determine the correct database table and column names.
    The generated SQL is wrapped in a single transaction.
    """
    sql_statements = []
    sql_statements.append("-- SQL De-identification Script --")
    sql_statements.append("-- Generated by CommCare Connect deidentify_database command --")
    sql_statements.append("-- Ensure this script is run only on a non-production, copied database! --")
    sql_statements.append("\nBEGIN;")  # Start a transaction

    for config in anonymization_configs:
        model_class = config.model
        table_name = model_class._meta.db_table
        sql_statements.append(f'\n-- Anonymizing table: "{table_name}" (Model: {model_class.__name__})')

        for field_config in config.fields:
            model_field_name = field_config.field_name  # This is the Django model field name
            try:
                # Get the actual database column name from the model field
                db_column_name = model_class._meta.get_field(model_field_name).column

                if field_config.anonymization_strategy == STRATEGY_DROP_FIELD:
                    # Use IF EXISTS for idempotency and quote identifiers
                    sql_statements.append(f'ALTER TABLE "{table_name}" DROP COLUMN IF EXISTS "{db_column_name}";')
                else:
                    # Placeholder for future strategies
                    sql_statements.append(
                        f"-- SKIPPING: Unknown or unsupported anonymization strategy "
                        f"'{field_config.anonymization_strategy}' for field '{model_field_name}' "
                        f'(column "{db_column_name}") in table "{table_name}"'
                    )
            except FieldDoesNotExist:
                sql_statements.append(
                    f"-- WARNING: Field '{model_field_name}' not found in model '{model_class.__name__}' "
                    f'(table "{table_name}"). Cannot determine column name. Skipping.'
                )
        # A newline will be added before the next model's comment or by the final join/print

    sql_statements.append("\nCOMMIT;")  # End transaction
    sql_statements.append("-- End of De-identification Script --")
    return sql_statements
