from enum import StrEnum


class ErrorCodes(StrEnum):
    OPPORTUNITY_REQUIRED = "OPPORTUNITY_REQUIRED"
    FAILED_USER_CREATE = "FAILED_USER_CREATE"
    NO_OPPORTUNITY_ACCESS = "NO_OPPORTUNITY_ACCESS"
    OPPORTUNITY_FULL = "OPPORTUNITY_FULL"
    OPPORTUNITY_ENDED = "OPPORTUNITY_ENDED"
    INVALID_FLAG = "INVALID_FLAG"
