# Generated by Django 4.2.5 on 2025-11-06 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("opportunity", "0084_merge_20251028_1339"),
    ]

    operations = [
        migrations.CreateModel(
            name="Audit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, help_text="Audit title (e.g., 'Week of Jan 1-7, 2024')", max_length=255)),
                ("tag", models.CharField(blank=True, help_text="Tag for categorizing audits (e.g., 'first_10', 'quarterly_review')", max_length=100)),
                ("opportunity_name", models.CharField(help_text="Name of opportunity/program being audited", max_length=255)),
                ("start_date", models.DateField(help_text="Start date of audit period (computed from visits at creation)")),
                ("end_date", models.DateField(help_text="End date of audit period (computed from visits at creation)")),
                (
                    "status",
                    models.CharField(
                        choices=[("in_progress", "In Progress"), ("completed", "Completed")],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                (
                    "overall_result",
                    models.CharField(
                        blank=True,
                        choices=[("pass", "Pass"), ("fail", "Fail")],
                        help_text="Overall audit result for this FLW/period",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="General notes about the audit")),
                ("kpi_notes", models.TextField(blank=True, help_text="KPI-related notes or reasons for failure")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "auditor",
                    models.ForeignKey(
                        help_text="User conducting the audit",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audits_conducted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "primary_opportunity",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary opportunity for single-opportunity audits",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audits",
                        to="opportunity.opportunity",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, help_text="Optional name for this audit template", max_length=255)),
                ("description", models.TextField(blank=True, help_text="Optional description of this template's purpose")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, help_text="When this template expires if not used (24h after creation)", null=True)),
                ("opportunity_ids", models.JSONField(help_text="List of opportunity IDs to audit")),
                ("audit_type", models.CharField(help_text="Type: date_range, last_n_per_flw, last_n_per_opp, last_n_across_all", max_length=50)),
                ("granularity", models.CharField(help_text="Granularity: combined, per_opp, per_flw", max_length=50)),
                ("start_date", models.DateField(blank=True, help_text="For date_range type", null=True)),
                ("end_date", models.DateField(blank=True, help_text="For date_range type", null=True)),
                ("count_per_flw", models.IntegerField(blank=True, help_text="For last_n_per_flw type", null=True)),
                ("count_per_opp", models.IntegerField(blank=True, help_text="For last_n_per_opp type", null=True)),
                ("count_across_all", models.IntegerField(blank=True, help_text="For last_n_across_all type", null=True)),
                ("sample_percentage", models.IntegerField(default=100, help_text="Percentage of visits to sample (1-100)")),
                ("sampled_visit_ids", models.JSONField(blank=True, help_text="List of sampled visit IDs for reproducibility", null=True)),
                ("preview_data", models.JSONField(blank=True, help_text="Preview statistics: FLW counts, visit counts, date ranges per opportunity/granularity", null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this template",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[("pass", "Pass"), ("fail", "Fail")],
                        help_text="Pass or fail for this visit",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Optional notes about why this visit failed")),
                ("audited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="results", to="audit.audit"
                    ),
                ),
                (
                    "user_visit",
                    models.ForeignKey(
                        help_text="The UserVisit being audited",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="opportunity.uservisit",
                    ),
                ),
            ],
            options={
                "ordering": ["user_visit__visit_date"],
            },
        ),
        migrations.AddField(
            model_name="audit",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="The audit template used to create this audit",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audits",
                to="audit.audittemplate",
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="visits",
            field=models.ManyToManyField(
                help_text="Explicit list of visits included in this audit",
                related_name="audits",
                to="opportunity.uservisit",
            ),
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[("image", "Image Assessment")],
                        help_text="Type of assessment (image, flag, data element, etc.)",
                        max_length=50,
                    ),
                ),
                ("blob_id", models.CharField(blank=True, help_text="Blob ID if this is an image assessment", max_length=255)),
                ("question_id", models.CharField(blank=True, help_text="CommCare question ID associated with this assessment", max_length=255)),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[("pass", "Pass"), ("fail", "Fail")],
                        help_text="Assessment result (null = not yet assessed)",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Notes about this specific assessment")),
                ("config_data", models.JSONField(blank=True, help_text="Configuration data for this assessment type", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "audit_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="assessments", to="audit.auditresult"
                    ),
                ),
            ],
            options={
                "ordering": ["question_id", "blob_id"],
            },
        ),
        migrations.AddIndex(
            model_name="audittemplate",
            index=models.Index(fields=["created_at"], name="audit_audit_created_06315a_idx"),
        ),
        migrations.AddIndex(
            model_name="audittemplate",
            index=models.Index(fields=["created_by", "created_at"], name="audit_audit_created_014ba8_idx"),
        ),
        migrations.AddIndex(
            model_name="auditresult",
            index=models.Index(fields=["audit", "result"], name="audit_audit_audit_i_af0c76_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="auditresult",
            unique_together={("audit", "user_visit")},
        ),
        migrations.AddIndex(
            model_name="audit",
            index=models.Index(fields=["auditor", "status"], name="audit_audit_auditor_4cd374_idx"),
        ),
        migrations.AddIndex(
            model_name="audit",
            index=models.Index(fields=["start_date", "end_date"], name="audit_audit_start_d_7efa80_idx"),
        ),
        migrations.AddIndex(
            model_name="audit",
            index=models.Index(fields=["status", "created_at"], name="audit_audit_status_26e5cf_idx"),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(fields=["audit_result", "assessment_type"], name="audit_asses_audit_r_d2eb14_idx"),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(fields=["audit_result", "result"], name="audit_asses_audit_r_64968a_idx"),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(fields=["blob_id"], name="audit_asses_blob_id_da7d78_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="assessment",
            unique_together={("audit_result", "assessment_type", "blob_id")},
        ),
    ]
