# Generated by Django 4.2.5 on 2025-10-03 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("opportunity", "0082_opportunityaccess_opportunity_opportu_94eae8_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "auditor_username",
                    models.CharField(help_text="Username of person conducting the audit", max_length=150),
                ),
                ("flw_username", models.CharField(help_text="Username of field worker being audited", max_length=150)),
                (
                    "opportunity_name",
                    models.CharField(help_text="Name of opportunity/program being audited", max_length=255),
                ),
                ("domain", models.CharField(help_text="CommCare domain/project space", max_length=255)),
                ("app_id", models.CharField(help_text="CommCare application ID", max_length=50)),
                ("start_date", models.DateField(help_text="Start date of audit period")),
                ("end_date", models.DateField(help_text="End date of audit period")),
                (
                    "status",
                    models.CharField(
                        choices=[("in_progress", "In Progress"), ("completed", "Completed")],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                (
                    "overall_result",
                    models.CharField(
                        blank=True,
                        choices=[("pass", "Pass"), ("fail", "Fail")],
                        help_text="Overall audit result for this FLW/period",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="General notes about the audit session")),
                ("kpi_notes", models.TextField(blank=True, help_text="KPI-related notes or reasons for failure")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["auditor_username", "status"], name="audit_audit_auditor_bde05f_idx"),
                    models.Index(fields=["flw_username", "domain"], name="audit_audit_flw_use_076f40_idx"),
                    models.Index(fields=["start_date", "end_date"], name="audit_audit_start_d_21dd17_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "result",
                    models.CharField(
                        choices=[("pass", "Pass"), ("fail", "Fail")],
                        help_text="Pass or fail for this visit",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Optional notes about why this visit failed")),
                ("audited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "audit_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="results", to="audit.auditsession"
                    ),
                ),
                (
                    "user_visit",
                    models.ForeignKey(
                        help_text="The UserVisit being audited",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="opportunity.uservisit",
                    ),
                ),
            ],
            options={
                "ordering": ["user_visit__visit_date"],
                "indexes": [models.Index(fields=["audit_session", "result"], name="audit_audit_audit_s_812c3b_idx")],
                "unique_together": {("audit_session", "user_visit")},
            },
        ),
    ]
