# Generated by Django 4.2.5 on 2026-04-27 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("opportunity", "0128_remove_assignedtask_update_update_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_by", models.CharField(max_length=255)),
                ("modified_by", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("audit_report_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed")], default="pending", max_length=16
                    ),
                ),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_audit_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_reports",
                        to="opportunity.opportunity",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_end", "-date_created"],
            },
        ),
        migrations.CreateModel(
            name="AuditReportEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_by", models.CharField(max_length=255)),
                ("modified_by", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("audit_report_entry_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("results", models.JSONField(default=dict)),
                ("flagged", models.BooleanField(default=False)),
                ("reviewed", models.BooleanField(default=False)),
                (
                    "review_action",
                    models.CharField(
                        blank=True,
                        choices=[("none", "No action"), ("tasks_assigned", "Tasks assigned")],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "audit_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="entries", to="audit.auditreport"
                    ),
                ),
                (
                    "opportunity_access",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_report_entries",
                        to="opportunity.opportunityaccess",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["audit_report", "flagged", "reviewed"], name="audit_audit_audit_r_921714_idx")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="auditreportentry",
            constraint=models.UniqueConstraint(
                fields=("audit_report", "opportunity_access"), name="unique_entry_per_access_per_report"
            ),
        ),
        migrations.AddIndex(
            model_name="auditreport",
            index=models.Index(fields=["opportunity", "-period_end"], name="audit_audit_opportu_7451a4_idx"),
        ),
    ]
