# Generated by Django 4.2.5 on 2025-10-03 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditImageNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "blob_id",
                    models.CharField(help_text="The blob ID of the image this note refers to", max_length=255),
                ),
                ("note", models.TextField(help_text="Note about this specific image")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "audit_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="image_notes", to="audit.auditresult"
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("audit_result", "blob_id")},
            },
        ),
    ]
