# Generated by Django 4.2.5 on 2025-11-11 02:44

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("labs", "0003_change_organization_id_to_charfield"),
        ("audit", "0002_delete_old_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditSessionRecord",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("labs.experimentrecord",),
        ),
        migrations.CreateModel(
            name="AuditTemplateRecord",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("labs.experimentrecord",),
        ),
    ]
