# Generated by Django 4.2.5 on 2025-10-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditimagenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditsession',
            name='opportunity_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of opportunity IDs included in this audit'),
        ),
    ]
