# Generated by Django 4.2.5 on 2025-10-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0082_opportunityaccess_opportunity_opportu_94eae8_idx_and_more'),
        ('audit', '0003_auditsession_opportunity_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditsession',
            name='user_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of user IDs/FLWs (metadata only)'),
        ),
        migrations.AddField(
            model_name='auditsession',
            name='visits',
            field=models.ManyToManyField(help_text='Explicit list of visits included in this audit', related_name='audit_sessions', to='opportunity.uservisit'),
        ),
        migrations.AlterField(
            model_name='auditsession',
            name='end_date',
            field=models.DateField(help_text='End date of audit period (metadata only)'),
        ),
        migrations.AlterField(
            model_name='auditsession',
            name='flw_username',
            field=models.CharField(blank=True, help_text='FLW username (metadata only)', max_length=150),
        ),
        migrations.AlterField(
            model_name='auditsession',
            name='opportunity_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of opportunity IDs (metadata only)'),
        ),
        migrations.AlterField(
            model_name='auditsession',
            name='start_date',
            field=models.DateField(help_text='Start date of audit period (metadata only)'),
        ),
    ]
