# Generated by Django 4.2.5 on 2025-10-08 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("audit", "0004_auditsession_user_ids_auditsession_visits_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(blank=True, help_text="Optional name for this audit definition", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("ready", "Ready"), ("used", "Used"), ("expired", "Expired")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("opportunity_ids", models.JSONField(help_text="List of opportunity IDs to audit")),
                (
                    "audit_type",
                    models.CharField(
                        help_text="Type: date_range, last_n_per_flw, last_n_per_opp, last_n_across_all", max_length=50
                    ),
                ),
                ("granularity", models.CharField(help_text="Granularity: combined, per_opp, per_flw", max_length=50)),
                ("start_date", models.DateField(blank=True, help_text="For date_range type", null=True)),
                ("end_date", models.DateField(blank=True, help_text="For date_range type", null=True)),
                ("count_per_flw", models.IntegerField(blank=True, help_text="For last_n_per_flw type", null=True)),
                ("count_per_opp", models.IntegerField(blank=True, help_text="For last_n_per_opp type", null=True)),
                (
                    "count_across_all",
                    models.IntegerField(blank=True, help_text="For last_n_across_all type", null=True),
                ),
                (
                    "sample_percentage",
                    models.IntegerField(default=100, help_text="Percentage of visits to sample (1-100)"),
                ),
                (
                    "sampled_visit_ids",
                    models.JSONField(
                        blank=True, help_text="List of sampled visit IDs (if sampling enabled)", null=True
                    ),
                ),
                (
                    "sample_cache_key",
                    models.CharField(
                        blank=True, help_text="Cache key for sampled visit IDs (temporary)", max_length=255
                    ),
                ),
                (
                    "preview_data",
                    models.JSONField(
                        blank=True,
                        help_text="Preview statistics: FLW counts, visit counts, date ranges per opportunity/granularity",
                        null=True,
                    ),
                ),
                (
                    "sessions_created",
                    models.IntegerField(default=0, help_text="Number of audit sessions created from this definition"),
                ),
                ("used_at", models.DateTimeField(blank=True, help_text="When sessions were created", null=True)),
                (
                    "used_by",
                    models.CharField(blank=True, help_text="Username who executed the creation", max_length=150),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this definition",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_definitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="auditsession",
            name="audit_definition",
            field=models.ForeignKey(
                blank=True,
                help_text="The audit definition used to create this session",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_sessions",
                to="audit.auditdefinition",
            ),
        ),
        migrations.AddIndex(
            model_name="auditdefinition",
            index=models.Index(fields=["status", "created_at"], name="audit_audit_status_7c5147_idx"),
        ),
        migrations.AddIndex(
            model_name="auditdefinition",
            index=models.Index(fields=["created_by", "status"], name="audit_audit_created_356a80_idx"),
        ),
    ]
