# Generated by Django 4.2.5 on 2025-10-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_auditdefinition_auditsession_audit_definition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditsession',
            name='tag',
            field=models.CharField(blank=True, help_text="Tag for categorizing audits (e.g., 'first_10', 'quarterly_review')", max_length=100),
        ),
        migrations.AddField(
            model_name='auditsession',
            name='title',
            field=models.CharField(blank=True, help_text="Audit title (e.g., 'Week of Jan 1-7, 2024')", max_length=255),
        ),
    ]
