# Generated by Django 4.2.5 on 2025-10-19 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0006_auditsession_tag_auditsession_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[("image", "Image Assessment")],
                        help_text="Type of assessment (image, flag, data element, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "blob_id",
                    models.CharField(blank=True, help_text="Blob ID if this is an image assessment", max_length=255),
                ),
                (
                    "question_id",
                    models.CharField(
                        blank=True, help_text="CommCare question ID associated with this assessment", max_length=255
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[("pass", "Pass"), ("fail", "Fail")],
                        help_text="Assessment result (null = not yet assessed)",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Notes about this specific assessment")),
                (
                    "config_data",
                    models.JSONField(blank=True, help_text="Configuration data for this assessment type", null=True),
                ),
                ("assessed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "audit_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="assessments", to="audit.auditresult"
                    ),
                ),
            ],
            options={
                "ordering": ["question_id", "blob_id"],
                "indexes": [
                    models.Index(fields=["audit_result", "assessment_type"], name="audit_asses_audit_r_d2eb14_idx"),
                    models.Index(fields=["blob_id"], name="audit_asses_blob_id_da7d78_idx"),
                ],
            },
        ),
    ]
