# Generated by Django 4.2.5 on 2025-10-20 19:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0008_alter_auditresult_result"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="assessment",
            unique_together={("audit_result", "assessment_type", "blob_id")},
        ),
    ]
