# Generated by Django 4.2.1 on 2023-07-18 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_organization_userorganizationmembership"),
        ("opportunity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommCareApp",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_by", models.CharField(max_length=255)),
                ("modified_by", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("cc_domain", models.CharField(max_length=255)),
                ("cc_app_id", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apps",
                        related_query_name="app",
                        to="users.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="opportunity",
            name="deliver_app",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="opportunity.commcareapp"
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="learn_app",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learn_app_opportunities",
                to="opportunity.commcareapp",
            ),
        ),
    ]
