# Generated by Django 4.2.1 on 2023-07-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0002_commcareapp_opportunity_deliver_app_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="budget_per_visit",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="daily_max_visits_per_user",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="max_visits_per_user",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="total_budget",
            field=models.IntegerField(null=True),
        ),
    ]
