# Generated by Django 4.2.1 on 2023-07-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0003_opportunity_budget_per_visit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commcareapp",
            name="passing_score",
            field=models.IntegerField(null=True),
        ),
    ]
