# Generated by Django 4.2.3 on 2023-07-26 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0004_commcareapp_passing_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliverForm",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("xmlns", models.CharField(max_length=255)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliver_form",
                        related_query_name="deliver_form",
                        to="opportunity.commcareapp",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliver_form",
                        related_query_name="deliver_form",
                        to="opportunity.opportunity",
                    ),
                ),
            ],
        ),
    ]
