# Generated by Django 4.2.3 on 2023-08-01 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("opportunity", "0005_deliverform"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearnModule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField()),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("time_estimate", models.IntegerField()),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learn_module",
                        related_query_name="learn_module",
                        to="opportunity.commcareapp",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserModule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_completed", models.DateTimeField(blank=True, null=True)),
                ("duration", models.TimeField()),
                ("cc_form_id", models.CharField(max_length=25)),
                ("app_build_id", models.CharField(max_length=25)),
                ("app_build_version", models.IntegerField()),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_modules",
                        related_query_name="user_module",
                        to="opportunity.learnmodule",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_modules",
                        related_query_name="user_module",
                        to="opportunity.opportunity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_modules",
                        related_query_name="user_module",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_accomplished", models.DateTimeField(blank=True, null=True)),
                ("score", models.IntegerField()),
                ("passing_score", models.IntegerField()),
                ("passed", models.BooleanField()),
                ("cc_form_id", models.CharField(max_length=25)),
                ("app_build_id", models.CharField(max_length=25)),
                ("app_build_version", models.IntegerField()),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessments",
                        related_query_name="assessment",
                        to="opportunity.commcareapp",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessments",
                        related_query_name="assessment",
                        to="opportunity.opportunity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        related_query_name="assessment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
