# Generated by Django 4.2.3 on 2023-07-31 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_connectuser"),
        ("opportunity", "0005_deliverform"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpportunityAccess",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        related_query_name="claim",
                        to="opportunity.opportunity",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        related_query_name="claim",
                        to="users.connectuser",
                    ),
                ),
            ],
        ),
    ]
