# Generated by Django 4.2.3 on 2023-08-02 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("opportunity", "0005_deliverform"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearnModule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField()),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("time_estimate", models.IntegerField(help_text="Estimated hours to complete the module")),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learn_modules",
                        to="opportunity.commcareapp",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompletedModule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateTimeField()),
                ("duration", models.DurationField()),
                ("xform_id", models.CharField(max_length=50)),
                ("app_build_id", models.CharField(max_length=50)),
                ("app_build_version", models.IntegerField()),
                (
                    "module",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="opportunity.learnmodule"),
                ),
                (
                    "opportunity",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="opportunity.opportunity"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_modules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateTimeField()),
                ("score", models.IntegerField()),
                ("passing_score", models.IntegerField()),
                ("passed", models.BooleanField()),
                ("xform_id", models.CharField(max_length=50)),
                ("app_build_id", models.CharField(max_length=50)),
                ("app_build_version", models.IntegerField()),
                ("app", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="opportunity.commcareapp")),
                (
                    "opportunity",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="opportunity.opportunity"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
