# Generated by Django 4.2.3 on 2023-08-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0007_opportunityaccess"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="app_build_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="app_build_version",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="completedmodule",
            name="app_build_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="completedmodule",
            name="app_build_version",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
