# Generated by Django 4.2.3 on 2023-08-07 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("opportunity", "0008_alter_assessment_app_build_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserVisit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("xform_id", models.CharField(max_length=50)),
                ("app_build_id", models.CharField(blank=True, max_length=50, null=True)),
                ("app_build_version", models.IntegerField(blank=True, null=True)),
                ("visit_date", models.DateTimeField()),
                (
                    "deliver_form",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="opportunity.deliverform"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
