# Generated by Django 4.2.3 on 2023-08-07 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0009_uservisit"),
        ("organization", "0001_initial"),
    ]

    run_before = [
        ("users", "0006_alter_organization_options_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="commcareapp",
                    name="organization",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apps",
                        related_query_name="app",
                        to="organization.organization",
                    ),
                ),
                migrations.AlterField(
                    model_name="opportunity",
                    name="organization",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        related_query_name="opportunity",
                        to="organization.organization",
                    ),
                ),
            ]
        )
    ]
