# Generated by Django 4.2.3 on 2023-08-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0010_move_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="uservisit",
            name="form_json",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
