# Generated by Django 4.2.3 on 2023-08-16 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0011_uservisit_form_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="uservisit",
            name="opportunity",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="opportunity.opportunity"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="uservisit",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                default="pending",
                max_length=50,
            ),
        ),
    ]
