# Generated by Django 4.2.3 on 2023-08-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0012_uservisit_opportunity_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunityaccess",
            name="date_learn_started",
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
