# Generated by Django 4.2.3 on 2023-08-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0013_hqapikey_opportunity_api_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunityaccess",
            name="date_learn_started",
            field=models.DateTimeField(null=True),
        ),
    ]
