# Generated by Django 4.2.3 on 2023-09-04 22:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0014_opportunityaccess_date_learn_started"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opportunityaccess",
            name="date_claimed",
        ),
    ]
