# Generated by Django 4.2.3 on 2023-09-13 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("opportunity", "0016_opportunityclaim"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunityaccess",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name="opportunityaccess",
            unique_together={("user", "opportunity")},
        ),
    ]
