# Generated by Django 4.2.5 on 2023-09-19 20:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0016_opportunityaccess_accepted_and_more"),
        ("opportunity", "0017_alter_opportunityaccess_user_and_more"),
    ]

    operations = []
