# Generated by Django 4.2.5 on 2023-10-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0018_merge_20230919_2049"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunityclaim",
            name="date_claimed",
            field=models.DateField(auto_now_add=True),
        ),
    ]
