# Generated by Django 4.2.5 on 2023-10-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0021_deliverunit_remove_uservisit_deliver_form_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uservisit",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("over_limit", "Over Limit"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
