# Generated by Django 4.2.5 on 2023-10-13 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0022_alter_uservisit_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentUnit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "opportunity",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="opportunity.opportunity"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="deliverunit",
            name="payment_unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliver_units",
                related_query_name="deliver_unit",
                to="opportunity.paymentunit",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                related_query_name="payment",
                to="opportunity.paymentunit",
            ),
        ),
    ]
