# Generated by Django 4.2.5 on 2023-10-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0023_paymentunit_deliverunit_payment_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="currency",
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="opportunityaccess",
            name="payment_accrued",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
