# Generated by Django 4.2.5 on 2023-11-02 09:09

from django.db import migrations
from django_celery_beat.models import IntervalSchedule, PeriodicTask


def create_send_inactive_notification_periodic_task(apps, schema_editor):
    interval, _ = IntervalSchedule.objects.get_or_create(every=1, period=IntervalSchedule.DAYS)
    PeriodicTask.objects.update_or_create(
        interval=interval,
        name="send_inactive_notifications",
        task="commcare_connect.opportunity.task.send_notification_inactive_users",
    )


def delete_send_inactive_notification_periodic_task(apps, schema_editor):
    interval, _ = IntervalSchedule.objects.get_or_create(every=1, period=IntervalSchedule.DAYS)
    PeriodicTask.objects.get(
        interval=interval,
        name="send_inactive_notifications",
        task="commcare_connect.opportunity.task.send_notification_inactive_users",
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0024_opportunity_currency_and_more"),
    ]

    operations = [
        migrations.RunPython(
            create_send_inactive_notification_periodic_task, delete_send_inactive_notification_periodic_task
        )
    ]
