# Generated by Django 4.2.5 on 2023-11-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0024_opportunity_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="short_description",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
