# Generated by Django 4.2.5 on 2023-11-02 09:09

from django.db import migrations
from django_celery_beat.models import PeriodicTask, CrontabSchedule


def create_send_inactive_notification_periodic_task(apps, schema_editor):
    schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="00",
        hour="7",
        day_of_week="*",
        day_of_month="*",
        month_of_year="*",
    )
    PeriodicTask.objects.update_or_create(
        crontab=schedule,
        name="send_inactive_notifications",
        task="commcare_connect.opportunity.task.send_notification_inactive_users",
    )


def delete_send_inactive_notification_periodic_task(apps, schema_editor):
    PeriodicTask.objects.get(
        name="send_inactive_notifications",
        task="commcare_connect.opportunity.task.send_notification_inactive_users",
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0025_opportunity_short_description"),
    ]

    operations = [
        migrations.RunPython(
            create_send_inactive_notification_periodic_task, delete_send_inactive_notification_periodic_task
        )
    ]
