# Generated by Django 4.2.5 on 2023-12-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0026_create_send_inactive_notification_periodic_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="uservisit",
            name="reason",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
