# Generated by Django 4.2.5 on 2023-12-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0027_uservisit_reason")
    ]

    operations = [
        migrations.AlterField(
            model_name="uservisit",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("over_limit", "Over Limit"),
                    ("duplicate", "Duplicate"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
