# Generated by Django 4.2.5 on 2024-01-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0028_duplicate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uservisit",
            name="entity_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
