# Generated by Django 4.2.5 on 2024-01-24 07:45

import traceback
from django.db import migrations
from django.core.management import call_command


def _populate_opportunity_access(apps, schema_editor):
    try:
        call_command(
            "populate_opportunity_access",
        )
    except Exception:
        traceback.print_exc()


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0029_assessment_opportunity_access_and_more"),
    ]

    operations = [migrations.RunPython(_populate_opportunity_access, migrations.RunPython.noop)]
