# Generated by Django 4.2.5 on 2024-01-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0029_alter_uservisit_entity_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="uservisit",
            name="location",
            field=models.CharField(null=True),
        ),
    ]
