# Generated by Django 4.2.5 on 2024-02-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0030_uservisit_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="uservisit",
            name="flag_reason",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uservisit",
            name="flagged",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="uservisit",
            name="reason",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
