# Generated by Django 4.2.5 on 2024-03-05 07:23
import django.db.models.deletion
from django.db import migrations, models
from itertools import groupby


def populate_completed_work(apps, schema_editor):
    OpportunityAccess = apps.get_model("opportunity.OpportunityAccess")
    PaymentUnit = apps.get_model("opportunity.PaymentUnit")
    UserVisit = apps.get_model("opportunity.UserVisit")
    CompletedWork = apps.get_model("opportunity.CompletedWork")
    for access in OpportunityAccess.objects.all():
        payment_units = PaymentUnit.objects.filter(opportunity=access.opportunity)
        for payment_unit in payment_units:
            user_visits = UserVisit.objects.filter(
                opportunity=access.opportunity,
                user=access.user,
                deliver_unit__in=payment_unit.deliver_units.all(),
                is_trial=False,
            )
            for _, visits in groupby(user_visits, key=lambda x: x.entity_id):
                for visit in visits:
                    completed_work, _ = CompletedWork.objects.get_or_create(
                        opportunity_access=access,
                        payment_unit=payment_unit,
                        entity_id=visit.entity_id,
                        defaults={"entity_name": visit.entity_name},
                    )
                    visit.completed_work = completed_work
                    visit.save()


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0032_blobmeta"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompletedWork",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("entity_id", models.CharField(blank=True, max_length=255, null=True)),
                ("entity_name", models.CharField(blank=True, max_length=255, null=True)),
                ("reason", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "opportunity_access",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="opportunity.opportunityaccess"),
                ),
                (
                    "payment_unit",
                    models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="opportunity.paymentunit"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="uservisit",
            name="completed_work",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="opportunity.completedwork"
            ),
        ),
        migrations.RunPython(populate_completed_work, migrations.RunPython.noop, hints={"run_on_secondary": False}),
    ]
