# Generated by Django 4.2.5 on 2024-02-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0032_blobmeta"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverunit",
            name="optional",
            field=models.BooleanField(default=False),
        ),
    ]
