# Generated by Django 4.2.5 on 2024-02-14 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0032_blobmeta"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="opportunity_access",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="opportunity.opportunityaccess"
            ),
        ),
        migrations.AddField(
            model_name="completedmodule",
            name="opportunity_access",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="opportunity.opportunityaccess"
            ),
        ),
        migrations.AddField(
            model_name="uservisit",
            name="opportunity_access",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="opportunity.opportunityaccess"
            ),
        ),
    ]
