# Generated by Django 4.2.5 on 2024-03-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0032_blobmeta"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="auto_approve_visits",
            field=models.BooleanField(default=False),
        ),
    ]
