# Generated by Django 4.2.5 on 2024-02-26 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0033_deliverunit_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentunit",
            name="parent_payment_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="child_payment_units",
                to="opportunity.paymentunit",
            ),
        ),
    ]
