# Generated by Django 4.2.5 on 2024-04-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0035_paymentunit_parent_payment_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="auto_approve_payments",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="auto_approve_visits",
            field=models.BooleanField(default=False),
        ),
    ]
