# Generated by Django 4.2.5 on 2024-03-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0035_paymentunit_parent_payment_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentunit",
            name="max_daily",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="paymentunit",
            name="max_total",
            field=models.IntegerField(null=True),
        ),
    ]
