# Generated by Django 4.2.5 on 2024-04-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0035_paymentunit_parent_payment_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="confirmation_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
