# Generated by Django 4.2.5 on 2024-04-15 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0036_payment_confirmation_date_payment_confirmed"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInvite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone_number", models.CharField(max_length=15)),
                ("message_sid", models.CharField(max_length=25)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sms_delivered", "SMS Delivered"),
                            ("sms_not_delivered", "SMS Not Delivered"),
                            ("sms_sent", "SMS Sent"),
                            ("accepted", "Accepted"),
                        ],
                        default="sms_sent",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="opportunity.opportunity"),
                ),
                (
                    "opportunity_access",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="opportunity.opportunityaccess",
                    ),
                ),
            ],
        ),
    ]
