# Generated by Django 4.2.5 on 2024-04-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0036_payment_confirmation_date_payment_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="auto_approve_payments",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="auto_approve_visits",
            field=models.BooleanField(default=False),
        ),
    ]
