# Generated by Django 4.2.5 on 2024-04-15 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0036_payment_confirmation_date_payment_confirmed"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInviteStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone_number", models.CharField(max_length=15)),
                ("message_sid", models.CharField(max_length=25)),
                ("status", models.CharField(max_length=20)),
                (
                    "opportunity",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="opportunity.opportunity"),
                ),
                (
                    "opportunity_access",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="opportunity.opportunityaccess",
                    ),
                ),
            ],
        ),
    ]
