# Generated by Django 4.2.5 on 2024-03-25 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0036_add_max_visits"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpportunityClaimLimit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("max_visits", models.IntegerField()),
                (
                    "opportunity_claim",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="opportunity.opportunityclaim"),
                ),
                (
                    "payment_unit",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="opportunity.paymentunit"),
                ),
            ],
        ),
    ]
