# Generated by Django 4.2.5 on 2024-04-03 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0037_opportunityclaimlimit"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="start_date",
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
