# Generated by Django 4.2.5 on 2024-04-17 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0038_opportunity_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="start_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterUniqueTogether(
            name="opportunityclaimlimit",
            unique_together={("opportunity_claim", "payment_unit")},
        ),
    ]
