# Generated by Django 4.2.5 on 2024-04-23 22:27

from django.db import migrations, models
from ..models import CompletedWorkStatus, VisitValidationStatus


def populate_overlimit_work(apps, schema_editor):
    UserVisit = apps.get_model("opportunity.UserVisit")
    for visit in UserVisit.objects.filter(status=VisitValidationStatus.over_limit):
        if visit.completed_work and visit.completed_work.status != CompletedWorkStatus.approved:
            visit.completed_work.status = CompletedWorkStatus.over_limit
            visit.completed_work.save()


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0039_alter_opportunity_start_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="completedwork",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("over_limit", "Over Limit"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.RunPython(populate_overlimit_work, migrations.RunPython.noop),
    ]
