# Generated by Django 4.2.5 on 2024-04-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0039_alter_opportunity_start_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uservisit",
            name="is_trial",
        ),
        migrations.AlterField(
            model_name="uservisit",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("over_limit", "Over Limit"),
                    ("duplicate", "Duplicate"),
                    ("trial", "Trial"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
