# Generated by Django 4.2.5 on 2024-04-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0040_alter_completedwork_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="auto_approve_payments",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="auto_approve_visits",
            field=models.BooleanField(default=False),
        ),
    ]
