# Generated by Django 4.2.5 on 2024-04-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0040_uservisit_is_trial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunityclaim",
            name="max_payments",
            field=models.IntegerField(null=True),
        ),
    ]
