# Generated by Django 4.2.5 on 2024-05-30 11:14

from django.db import migrations, models


def change_defaults(apps, schema_editor):
    Opportunity = apps.get_model("opportunity.Opportunity")
    Opportunity.objects.filter(auto_approve_payments=False).update(auto_approve_payments=True)
    Opportunity.objects.filter(auto_approve_visits=False).update(auto_approve_visits=True)


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0044_opportunityverificationflags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="auto_approve_payments",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="auto_approve_visits",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(change_defaults, migrations.RunPython.noop)
    ]
