# Generated by Django 4.2.5 on 2024-06-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0045_userinvite"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunityaccess",
            name="suspended",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="opportunityaccess",
            name="suspension_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opportunityaccess",
            name="suspension_reason",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
