# Generated by Django 4.2.5 on 2024-06-21 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0046_opportunityaccess_suspended_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormJsonValidationRules",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField()),
                ("name", models.CharField(max_length=25)),
                ("question_path", models.CharField(max_length=255)),
                ("question_value", models.CharField(max_length=255)),
                ("deliver_unit", models.ManyToManyField(to="opportunity.deliverunit")),
                (
                    "opportunity",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="opportunity.opportunity"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliverUnitFlagRules",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("check_attachments", models.BooleanField(default=False)),
                ("duration", models.PositiveIntegerField(default=0)),
                (
                    "deliver_unit",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="opportunity.deliverunit"),
                ),
                (
                    "opportunity",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="opportunity.opportunity"),
                ),
            ],
        ),
    ]
