# Generated by Django 4.2.5 on 2024-06-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0046_opportunityaccess_suspended_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="completedwork",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("over_limit", "Over Limit"),
                    ("incomplete", "Incomplete"),
                ],
                default="incomplete",
                max_length=50,
            ),
        ),
    ]
