# Generated by Django 4.2.5 on 2024-06-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0047_alter_completedwork_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="is_test",
            field=models.BooleanField(default=True),
        ),
    ]
