# Generated by Django 4.2.5 on 2024-06-25 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0048_opportunity_is_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("slug", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="opportunity",
            name="delivery_type",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="opportunity.deliverytype"
            ),
        ),
    ]
