# Generated by Django 4.2.5 on 2024-07-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0049_deliverytype_opportunity_delivery_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="auto_approve_payments",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="auto_approve_visits",
            field=models.BooleanField(default=True),
        ),
    ]
