# Generated by Django 4.2.5 on 2024-06-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0049_deliverytype_opportunity_delivery_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="completedwork",
            name="status_modification_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="uservisit",
            name="status_modification_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
