# Generated by Django 4.2.5 on 2024-07-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0049_deliverytype_opportunity_delivery_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="completedwork",
            name="status_modified_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="uservisit",
            name="status_modified_date",
            field=models.DateTimeField(null=True),
        ),
    ]
