# Generated by Django 4.2.5 on 2024-07-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0050_completedwork_status_modified_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="auto_approve_payments",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="auto_approve_visits",
            field=models.BooleanField(default=True),
        ),
    ]
