# Generated by Django 4.2.5 on 2024-06-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0050_completedwork_status_modification_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="completedwork",
            name="status_modification_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="uservisit",
            name="status_modification_date",
            field=models.DateTimeField(null=True),
        ),
    ]
