# Generated by Django 4.2.5 on 2024-07-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0050_opportunityverificationflags_catchment_areas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catchmentarea",
            name="latitude",
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name="catchmentarea",
            name="longitude",
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
    ]
