# Generated by Django 4.2.5 on 2024-09-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0053_assessment_opportunity_access_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="managed",
            field=models.BooleanField(default=False),
        ),
    ]
