# Generated by Django 4.2.5 on 2024-08-08 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0005_alter_userorganizationmembership_role"),
        ("opportunity", "0053_assessment_opportunity_access_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="managed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opportunities",
                related_query_name="opportunity",
                to="organization.organization",
            ),
        ),
    ]
