# Generated by Django 4.2.5 on 2024-09-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0054_opportunity_managed_alter_opportunity_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunityaccess",
            name="invited_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
