# Generated by Django 4.2.5 on 2024-09-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0054_formjsonvalidationrules_deliverunitflagrules"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="managed",
            field=models.BooleanField(default=False),
        ),
    ]
