# Generated by Django 4.2.5 on 2024-08-29 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0006_organization_program_manager"),
        ("opportunity", "0055_uservisit_review_created_on_uservisit_review_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="organization",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="organization.organization"
            ),
        ),
    ]
