# Generated by Django 4.2.5 on 2024-09-18 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0057_payment_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentInvoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.PositiveIntegerField()),
                ("date", models.DateField()),
                ("invoice_number", models.CharField(max_length=50)),
                (
                    "opportunity",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="opportunity.opportunity"),
                ),
            ],
            options={
                "unique_together": {("opportunity", "invoice_number")},
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="invoice",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="opportunity.paymentinvoice"
            ),
        ),
    ]
