# Generated by Django 4.2.5 on 2024-09-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0058_paymentinvoice_payment_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunityaccess",
            name="invited_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
