# Generated by Django 4.2.5 on 2024-10-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0059_payment_amount_usd"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunityaccess",
            name="invited_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
