# Generated by Django 4.2.5 on 2024-11-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0060_completedwork_payment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinvite",
            name="notification_date",
            field=models.DateTimeField(null=True),
        ),
    ]
