# Generated by Django 4.2.5 on 2024-11-06 05:16

from django.db import migrations, models
from django.db.models.functions import TruncDate

from commcare_connect.opportunity.visit_import import get_exchange_rate


def update_exchange_rate(apps, schema_editor):
    Payment = apps.get_model("opportunity.Payment")
    payments = (
        Payment.objects.annotate(date_only=TruncDate("date_paid"))
        .values("date_only", "opportunity_access__opportunity__currency")
        .distinct()
    )

    for payment in payments:
        date_paid = payment["date_only"]
        currency = payment["opportunity_access__opportunity__currency"]

        if currency in ["USD", None]:
            exchange_rate = 1
        else:
            exchange_rate = get_exchange_rate(currency, date_paid)
        if not exchange_rate:
            raise Exception(f"Invalid currency code {currency}")


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0060_completedwork_payment_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("currency_code", models.CharField(max_length=3)),
                ("rate", models.DecimalField(decimal_places=6, max_digits=10)),
                ("rate_date", models.DateField()),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RunPython(update_exchange_rate, migrations.RunPython.noop),
    ]
