# Generated by Django 4.2.5 on 2024-12-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0062_opportunityaccess_invited_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinvite",
            name="notification_date",
            field=models.DateTimeField(null=True),
        ),
    ]
