# Generated by Django 4.2.5 on 2024-12-16 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0062_opportunityaccess_invited_date"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="completedwork",
            unique_together={("entity_id", "payment_unit")},
        ),
    ]
