# Generated by Django 4.2.5 on 2025-01-07 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0063_userinvite_notification_date"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="completedwork",
            unique_together={("entity_id", "payment_unit")},
        ),
    ]
