# Generated by Django 4.2.5 on 2025-01-10 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0065_uservisit_unique_xform_entity_deliver_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="completedwork",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="uservisit",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
