# Generated by Django 4.2.5 on 2025-01-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0067_exchangerate_exchangerate_unique_currency_code_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="completedwork",
            name="saved_approved_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="completedwork",
            name="saved_completed_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="completedwork",
            name="saved_org_payment_accrued",
            field=models.IntegerField(default=0, help_text="Payment accrued for the organization"),
        ),
        migrations.AddField(
            model_name="completedwork",
            name="saved_org_payment_accrued_usd",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Payment accrued for the organization in USD.", max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="completedwork",
            name="saved_payment_accrued",
            field=models.IntegerField(default=0, help_text="Payment accrued for the FLW."),
        ),
        migrations.AddField(
            model_name="completedwork",
            name="saved_payment_accrued_usd",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Payment accrued for the FLW in USD.", max_digits=10
            ),
        ),
    ]
