# Generated by Django 4.2.5 on 2025-01-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0067_exchangerate_exchangerate_unique_currency_code_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="total_budget",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
