# Generated by Django 4.2.5 on 2025-01-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0068_completedwork_saved_approved_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="total_budget",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
