# Generated by Django 4.2.5 on 2025-01-29 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0069_alter_opportunity_total_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date_paid",
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
