# Generated by Django 4.2.5 on 2025-02-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0070_alter_payment_date_paid"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="completedmodule",
            constraint=models.UniqueConstraint(
                fields=("xform_id", "module", "opportunity_access"), name="unique_xform_completed_module"
            ),
        ),
    ]
