# Generated by Django 4.2.5 on 2025-02-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0070_alter_payment_date_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentinvoice",
            name="service_delivery",
            field=models.BooleanField(default=True),
        ),
    ]
