# Generated by Django 4.2.5 on 2025-03-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0072_completedmodule_unique_xform_completed_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_operator",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
