# Generated by Django 4.2.5 on 2025-05-22 09:29

from django.db import migrations, models
import django.utils.timezone
from django.db.models import F


def backfill_payment_created_date(apps, schema):
    Payment = apps.get_model("opportunity", "Payment")
    Payment.objects.all().update(created_at=F("date_paid"))


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0073_payment_payment_method_payment_payment_operator"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RunPython(
            backfill_payment_created_date,
            migrations.RunPython.noop,
            hints={"run_on_secondary": False},
        )
    ]
