# Generated by Django 4.2.5 on 2025-06-03 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0075_opportunityaccess_completed_learn_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="paymentinvoice",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
