# Generated by Django 4.2.5 on 2025-07-10 05:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("commcarehq", "0001_initial"),
        ("opportunity", "0076_alter_payment_amount_alter_paymentinvoice_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="commcareapp",
            name="hq_server",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="commcarehq.hqserver"
            ),
        ),
        migrations.AddField(
            model_name="hqapikey",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hqapikey",
            name="hq_server",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="commcarehq.hqserver"
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="hq_server",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="commcarehq.hqserver"
            ),
        ),
    ]
