# Generated by Django 4.2.5 on 2025-05-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0076_alter_payment_amount_alter_paymentinvoice_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentinvoice",
            name="amount_usd",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="exchangerate",
            name="rate_date",
            field=models.DateField(db_index=True),
        ),
    ]
