# Generated by Django 4.2.5 on 2025-05-28 00:17

from django.db import migrations
from django_celery_beat.models import PeriodicTask, CrontabSchedule


def create_fetch_rates_task(apps, schema_editor):
    schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="00",
        hour="2",
        day_of_week="*",
        day_of_month="2",
        month_of_year="*",
    )
    PeriodicTask.objects.update_or_create(
        crontab=schedule,
        name="fetch_exchange_rates",
        task="commcare_connect.opportunity.tasks.fetch_exchange_rates",
    )


def delete_fetch_rates_task(apps, schema_editor):
    PeriodicTask.objects.get(
        name="fetch_exchange_rates",
        task="commcare_connect.opportunity.tasks.fetch_exchange_rates",
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0077_paymentinvoice_amount_usd_and_more"),
    ]

    operations = [
        migrations.RunPython(create_fetch_rates_task, delete_fetch_rates_task, hints={"run_on_secondary": False})
    ]
