# Generated by Django 4.2.5 on 2025-06-23 14:49


from django.conf import settings
from django.db import migrations


def create_prod_hq_server_and_update_objects(apps, schema_editor):
    HQServer = apps.get_model("opportunity", "HQServer")
    Opportunity = apps.get_model("opportunity", "Opportunity")
    HQApiKey = apps.get_model("opportunity", "HQApiKey")
    CommCareApp = apps.get_model("opportunity", "CommCareApp")

    hq_server, _ = HQServer.objects.update_or_create(
        name="CommCareHQ", url=settings.COMMCARE_HQ_URL, oauth_application_id=1
    )
    Opportunity.objects.update(hq_server=hq_server)
    CommCareApp.objects.update(hq_server=hq_server)
    HQApiKey.objects.update(hq_server=hq_server)


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0077_hqapikey_date_created_hqserver_commcareapp_hq_server_and_more"),
    ]

    operations = [
        migrations.RunPython(
            create_prod_hq_server_and_update_objects, migrations.RunPython.noop, hints={"run_on_secondary": False}
        ),
    ]
