# Generated by Django 4.2.5 on 2025-07-10 09:31

from django.db import migrations

from django.conf import settings
from oauth2_provider.models import Application


def create_prod_hq_server_and_update_objects(apps, schema_editor):
    HQServer = apps.get_model("commcarehq", "HQServer")
    Opportunity = apps.get_model("opportunity", "Opportunity")
    HQApiKey = apps.get_model("opportunity", "HQApiKey")
    CommCareApp = apps.get_model("opportunity", "CommCareApp")
    ConnectIDUserLink = apps.get_model("users", "ConnectIDUserLink")

    oauth_application = Application.objects.filter(id=1).first()
    if oauth_application:
        hq_server, _ = HQServer.objects.update_or_create(
            name="CommCareHQ",
            url=settings.COMMCARE_HQ_URL,
            oauth_application_id=oauth_application.id,
        )
        Opportunity.objects.update(hq_server=hq_server)
        CommCareApp.objects.update(hq_server=hq_server)
        HQApiKey.objects.update(hq_server=hq_server)
        ConnectIDUserLink.objects.update(hq_server=hq_server)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_connectiduserlink_hq_server"),
        ("opportunity", "0079_commcareapp_hq_server_hqapikey_date_created_and_more"),
    ]

    operations = [
        migrations.RunPython(
            create_prod_hq_server_and_update_objects, migrations.RunPython.noop, hints={"run_on_secondary": False}
        ),
    ]
