# Generated by Django 4.2.5 on 2025-07-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0081_remove_opportunity_budget_per_visit_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="opportunityaccess",
            index=models.Index(fields=["opportunity", "date_learn_started"], name="opportunity_opportu_94eae8_idx"),
        ),
        migrations.AddIndex(
            model_name="uservisit",
            index=models.Index(fields=["opportunity", "status"], name="opportunity_opportu_1b5d1e_idx"),
        ),
    ]
