# Generated by Django 4.2.5 on 2025-10-09 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0082_opportunityaccess_opportunity_opportu_94eae8_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CredentialConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "learn_level",
                    models.CharField(
                        blank=True, choices=[("LEARN_PASSED", "Learning passed")], max_length=32, null=True
                    ),
                ),
                (
                    "delivery_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("25_DELIVERIES", "25 Deliveries"),
                            ("50_DELIVERIES", "50 Deliveries"),
                            ("100_DELIVERIES", "100 Deliveries"),
                            ("200_DELIVERIES", "200 Deliveries"),
                            ("500_DELIVERIES", "500 Deliveries"),
                            ("1000_DELIVERIES", "1000 Deliveries"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="opportunity.opportunity", unique=True
                    ),
                ),
            ],
        ),
    ]
