# Generated by Django 4.2.5 on 2025-10-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0082_opportunityaccess_opportunity_opportu_94eae8_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blobmeta",
            name="question_id",
            field=models.CharField(
                blank=True,
                help_text="CommCare form question ID that this attachment belongs to",
                max_length=255,
                null=True,
            ),
        ),
    ]
