# Generated by Django 4.2.5 on 2025-09-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0082_opportunityaccess_opportunity_opportu_94eae8_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uservisit",
            name="location",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
