# Generated by Django 4.2.5 on 2023-11-02 09:09

from django.db import migrations
from django_celery_beat.models import PeriodicTask, CrontabSchedule


def create_periodic_task(apps, schema_editor):
    # Run daily
    schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="00",
        hour="1",
        day_of_week="*",
        day_of_month="*",
        month_of_year="*",
    )
    PeriodicTask.objects.update_or_create(
        name="issue_user_credentials",
        defaults={
            "task": "commcare_connect.opportunity.tasks.issue_user_credentials",
            "crontab": schedule,
            "interval": None,
        },
    )


def delete_periodic_task(apps, schema_editor):
    PeriodicTask.objects.filter(
        name="issue_user_credentials",
        task="commcare_connect.opportunity.tasks.issue_user_credentials",
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0083_credentialconfiguration"),
    ]

    operations = [
        migrations.RunPython(
            create_periodic_task, delete_periodic_task,
            hints={"run_on_secondary": False}
        )
    ]
