# Generated by Django 4.2.5 on 2025-10-28 19:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0083_add_question_id_to_blobmeta"),
        ("opportunity", "0083_credentialconfiguration"),
    ]

    operations = []
