# Generated by Django 4.2.5 on 2025-11-13 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organization", "0007_remove_userorganizationmembership_accepted"),
        ("opportunity", "0083_credentialconfiguration"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabsRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("experiment", models.TextField()),
                ("type", models.CharField(max_length=255)),
                ("data", models.JSONField()),
                (
                    "labs_record",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="opportunity.labsrecord"
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="opportunity.opportunity"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="organization.organization"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
