# Generated by Django 4.2.5 on 2025-11-11 02:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0083_alter_uservisit_location"),
        ("opportunity", "0084_merge_20251028_1339"),
    ]

    operations = []
