# Generated by Django 4.2.5 on 2025-11-10 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0084_paymentinvoice_end_date_paymentinvoice_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="completedwork",
            name="invoice",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="opportunity.paymentinvoice"
            ),
        ),
    ]
