# Generated by Django 4.2.5 on 2025-11-16 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0001_initial"),
        ("opportunity", "0085_create_issue_credentials_periodic_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="labsrecord",
            name="program",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="program.program"),
        ),
        migrations.AlterField(
            model_name="labsrecord",
            name="opportunity",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="opportunity.opportunity"
            ),
        ),
    ]
