# Generated by Django 4.2.5 on 2025-11-18 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0085_create_issue_credentials_periodic_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="completedwork",
            name="invoice",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="opportunity.paymentinvoice"
            ),
        ),
        migrations.AddField(
            model_name="paymentinvoice",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentinvoice",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentinvoice",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentinvoice",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
