# Generated by Django 4.2.5 on 2025-12-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0087_completedwork_invoice_paymentinvoice_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="labsrecord",
            name="public",
            field=models.BooleanField(default=False),
        ),
    ]
