# Generated by Django 4.2.5 on 2025-12-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0088_labsrecord_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentinvoice",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("submitted", "Submitted"), ("approved", "Approved")],
                default="pending",
                max_length=50,
            ),
        ),
    ]
