# Generated by Django 4.2.5 on 2026-01-01 10:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0092_currency_country_opportunity_currency_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="formjsonvalidationrules",
            name="form_json_validation_rules_id",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="opportunity_id",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="opportunityaccess",
            name="opportunity_access_id",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_id",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="paymentunit",
            name="payment_unit_id",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="uservisit",
            name="user_visit_id",
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
