# Generated by Django 4.2.5 on 2026-01-02 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0092_currency_country_opportunity_currency_fk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opportunity",
            name="currency",
        ),
    ]
