# Generated by Django 4.2.5 on 2026-01-01 10:42

from django.db import migrations


def gen_uuid(apps, schema_editor):
    connection = schema_editor.connection

    def backfill_uuid(table_name, field_name):
        """
        Bulk update NULL UUIDs in a given table.
        Uses PostgreSQL gen_random_uuid() function.
        """
        with connection.cursor() as cursor:
            cursor.execute(f"""
                UPDATE {table_name}
                SET {field_name} = gen_random_uuid()
                WHERE {field_name} IS NULL;
            """)

    backfill_uuid("opportunity_opportunity", "opportunity_id")
    backfill_uuid("opportunity_opportunityaccess", "opportunity_access_id")
    backfill_uuid("opportunity_paymentunit", "payment_unit_id")
    backfill_uuid("opportunity_payment", "payment_id")
    backfill_uuid("opportunity_uservisit", "user_visit_id")
    backfill_uuid("opportunity_formjsonvalidationrules", "form_json_validation_rules_id")


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0093_formjsonvalidationrules_form_json_validation_rules_id_and_more"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop, hints={"run_on_secondary": False}),
    ]
