# Generated by Django 4.2.5 on 2026-01-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0094_backfill_uuid_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentinvoice",
            name="archived_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="paymentinvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("archived", "Archived"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
