# Generated by Django 4.2.5 on 2026-01-02 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0095_paymentinvoice_archived_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opportunity",
            name="currency",
        ),
    ]
