# Generated by Django 4.2.5 on 2026-01-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0095_paymentinvoice_archived_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentunit",
            name="org_amount",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
