# Generated by Django 4.2.5 on 2025-12-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0096_paymentinvoice_archived_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymentinvoice",
            old_name="notes",
            new_name="description",
        ),
        migrations.AddField(
            model_name="paymentinvoice",
            name="date_of_expense",
            field=models.DateField(blank=True, null=True),
        ),
    ]
