# Generated by Django 4.2.5 on 2026-01-19 09:09

from uuid import uuid4
from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    connection = schema_editor.connection
    table_name = "opportunity_paymentinvoice"
    field_name = "payment_invoice_id"

    with connection.cursor() as cursor:
        cursor.execute(f"""
            UPDATE {table_name}
            SET {field_name} = gen_random_uuid()
            WHERE {field_name} IS NULL;
        """)


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0097_remove_opportunity_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentinvoice",
            name="payment_invoice_id",
            field=models.UUIDField(editable=False, null=True, default=uuid4),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop, hints={"run_on_secondary": False}),
    ]
