# Generated by Django 4.2.5 on 2026-01-14 11:52

from django.db import migrations, models


def backfill_org_amount(apps, schema_editor):
    PaymentUnit = apps.get_model("opportunity", "PaymentUnit")

    for pu in PaymentUnit.objects.filter(opportunity__managed=True):
        if org_amount := pu.opportunity.managedopportunity.org_pay_per_visit:
            pu.org_amount = org_amount
            pu.save(update_fields=["org_amount"])


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0097_remove_opportunity_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentunit",
            name="org_amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_org_amount, hints={"run_on_secondary": True}),
    ]