# Generated by Django 4.2.5 on 2026-01-14 11:52

from django.db import migrations, models


def backfill_org_amount(apps, schema_editor):
    PaymentUnit = apps.get_model("opportunity", "PaymentUnit")

    payment_units_to_update = []
    for pu in PaymentUnit.objects.filter(opportunity__managed=True):
        if m_opp := getattr(pu.opportunity, "managedopportunity", None):        
            if org_amount := m_opp.org_pay_per_visit:
                pu.org_amount = org_amount
                payment_units_to_update.append(pu)

        if len(payment_units_to_update) >= 200:
            PaymentUnit.objects.bulk_update(payment_units_to_update, ["org_amount"])
            payment_units_to_update = []

    if payment_units_to_update:
        PaymentUnit.objects.bulk_update(payment_units_to_update, ["org_amount"])


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0097_remove_opportunity_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentunit",
            name="org_amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_org_amount, reverse_code=migrations.RunPython.noop, hints={"run_on_secondary": False}),
    ]