# Generated by Django 4.2.5 on 2026-01-22 06:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0097_remove_opportunity_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formjsonvalidationrules",
            name="form_json_validation_rules_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="opportunity_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="opportunityaccess",
            name="opportunity_access_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="paymentunit",
            name="payment_unit_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="uservisit",
            name="user_visit_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
