# Generated by Django 4.2.5 on 2026-01-19 09:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0098_paymentinvoice_payment_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentinvoice",
            name="payment_invoice_id",
            field=models.UUIDField(editable=False, default=uuid.uuid4, unique=True),
        )
    ]
