# Generated by Django 4.2.5 on 2026-01-22 08:10

from django.db import migrations, models
import uuid


def gen_uuid(apps, schema_editor):
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        cursor.execute("""
            UPDATE opportunity_opportunity
            SET opportunity_id = gen_random_uuid()
            WHERE opportunity_id IS NULL;
        """)


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0099_alter_formjsonvalidationrules_form_json_validation_rules_id_and_more"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop, hints={"run_on_secondary": False}),
        migrations.AlterField(
            model_name="opportunity",
            name="opportunity_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
