# Generated by Django 4.2.5 on 2026-01-22 08:14

from django.db import migrations, models
import uuid


def gen_uuid(apps, schema_editor):
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        cursor.execute("""
            UPDATE opportunity_uservisit
            SET user_visit_id = gen_random_uuid()
            WHERE user_visit_id IS NULL;
        """)


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0100_alter_opportunity_opportunity_id"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop, hints={"run_on_secondary": False}),
        migrations.AlterField(
            model_name="uservisit",
            name="user_visit_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
