# Generated by Django 4.2.5 on 2026-01-22 08:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0101_alter_uservisit_user_visit_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formjsonvalidationrules",
            name="form_json_validation_rules_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="opportunityaccess",
            name="opportunity_access_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="paymentunit",
            name="payment_unit_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
