# Generated by Django 4.2.5 on 2026-01-22 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0102_alter_formjsonvalidationrules_form_json_validation_rules_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="opportunity_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
