# Generated by Django 4.2.5 on 2026-01-22 09:53

from django.db import migrations, models
import uuid


FORWARD_CREATE_UNIQUE_INDEX = """
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS opportunity_uservisit_user_visit_id_103145e1_uniq
ON opportunity_uservisit (user_visit_id);
"""

FORWARD_ADD_UNIQUE_CONSTRAINT = """
ALTER TABLE opportunity_uservisit
ADD CONSTRAINT opportunity_uservisit_user_visit_id_103145e1_uniq
UNIQUE USING INDEX opportunity_uservisit_user_visit_id_103145e1_uniq;
"""

REVERSE_DROP_UNIQUE_CONSTRAINT = """
ALTER TABLE opportunity_uservisit
DROP CONSTRAINT IF EXISTS opportunity_uservisit_user_visit_id_103145e1_uniq;
"""

REVERSE_DROP_UNIQUE_INDEX = """
DROP INDEX CONCURRENTLY IF EXISTS opportunity_uservisit_user_visit_id_103145e1_uniq;
"""


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("opportunity", "0103_alter_opportunity_opportunity_id"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="uservisit",
                    name="user_visit_id",
                    field=models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
            ],

            database_operations=[
                # NOTE: Forward runs top → bottom
                # Reverse runs bottom → top
                migrations.RunSQL(
                    FORWARD_CREATE_UNIQUE_INDEX,
                    REVERSE_DROP_UNIQUE_INDEX,
                ),
                migrations.RunSQL(
                    FORWARD_ADD_UNIQUE_CONSTRAINT,
                    REVERSE_DROP_UNIQUE_CONSTRAINT,
                ),
            ],
        ),
    ]
