# Generated by Django 4.2.5 on 2026-02-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0107_backfill_payment_invoice_uuid_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentinvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_nm_review", "Pending Network Manager Review"),
                    ("pending_pm_review", "Pending Program Manager Review"),
                    ("cancelled_by_nm", "Cancelled by Network Manager"),
                    ("ready_to_pay", "Ready to Pay"),
                    ("rejected_by_pm", "Rejected by Program Manager"),
                    ("paid", "Paid"),
                    ("archived", "Archived"),
                ],
                default="pending_nm_review",
                max_length=50,
            ),
        ),
    ]
