# Generated by Django 4.2.5 on 2026-02-10 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("opportunity", "0109_paymentunit_org_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField()),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("time_estimate", models.IntegerField(help_text="Estimated hours to complete the task")),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="opportunity.commcareapp"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompletedTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("xform_id", models.CharField(max_length=50)),
                ("app_build_id", models.CharField(blank=True, max_length=50, null=True)),
                ("app_build_version", models.IntegerField(blank=True, null=True)),
                ("date", models.DateTimeField()),
                ("duration", models.DurationField()),
                (
                    "opportunity",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="opportunity.opportunity"),
                ),
                (
                    "opportunity_access",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="opportunity.opportunityaccess"
                    ),
                ),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="opportunity.task")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name="completedtask",
            constraint=models.UniqueConstraint(
                fields=("xform_id", "module", "opportunity_access"), name="unique_xform_completed_task"
            ),
        ),
    ]
