# Generated by Django 4.2.5 on 2026-02-02 07:34

from django.db import migrations, models


def migrate_old_status_to_new(apps, schema_editor):
    PaymentInvoice = apps.get_model('opportunity', 'PaymentInvoice')
    status_mapping = {
        'pending': 'pending_nm_review',
        'submitted': 'pending_pm_review',
        'approved': 'paid',
    }
    for old_status, new_status in status_mapping.items():
        PaymentInvoice.objects.filter(status=old_status).update(status=new_status)


def reverse_migrate_new_status_to_old(apps, schema_editor):
    PaymentInvoice = apps.get_model('opportunity', 'PaymentInvoice')
    reverse_mapping = {
        'pending_nm_review': 'pending',
        'pending_pm_review': 'submitted',
        'paid': 'approved',
    }
    for new_status, old_status in reverse_mapping.items():
        PaymentInvoice.objects.filter(status=new_status).update(status=old_status)


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0109_paymentunit_org_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentinvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_nm_review", "Pending Network Manager Review"),
                    ("pending_pm_review", "Pending Program Manager Review"),
                    ("cancelled_by_nm", "Cancelled by Network Manager"),
                    ("ready_to_pay", "Ready to Pay"),
                    ("rejected_by_pm", "Rejected by Program Manager"),
                    ("paid", "Paid"),
                    ("archived", "Archived"),
                ],
                default="pending_nm_review",
                max_length=50,
            ),
        ),
        migrations.RunPython(
            migrate_old_status_to_new,
            reverse_migrate_new_status_to_old,
            hints={"run_on_secondary": False},
        ),
    ]

