# Generated by Django 4.2.5 on 2026-02-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0110_task_completedtask_task_unique_task_per_app_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentinvoice",
            name="invoice_ticket_link",
            field=models.CharField(blank=True, null=True),
        ),
    ]
