# Generated by Django 4.2.5 on 2026-02-13 10:01

# Generated by pghistory using makemigrations command

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pghistory", "0007_auto_20250421_0444"),
        ("opportunity", "0110_task_completedtask_task_unique_task_per_app_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentInvoiceStatusEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("archived", "Archived"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="paymentinvoice",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "opportunity_paymentinvoicestatusevent" ("pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status") VALUES (_pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status"); RETURN NULL;',
                    hash="f73fddc1b1e2a8bc30ab4b041644b03ffb32edc7",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_e3634",
                    table="opportunity_paymentinvoice",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="paymentinvoice",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."status" IS DISTINCT FROM (NEW."status"))',
                    func='INSERT INTO "opportunity_paymentinvoicestatusevent" ("pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status") VALUES (_pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status"); RETURN NULL;',
                    hash="c968dbe7e0fdcc62f5e7fb0c542fad8d1de70e17",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_7ba20",
                    table="opportunity_paymentinvoice",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="paymentinvoicestatusevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="paymentinvoicestatusevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="status_events",
                to="opportunity.paymentinvoice",
            ),
        ),
    ]
