# Generated by Django 4.2.5 on 2026-02-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0111_alter_paymentinvoice_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentinvoice",
            name="invoice_ticket_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
