# Generated by Django 4.2.5 on 2026-02-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0112_paymentinvoicestatusevent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="completedwork",
            name="saved_org_payment_accrued",
            field=models.IntegerField(default=0, help_text="Payment accrued for the workspace"),
        ),
        migrations.AlterField(
            model_name="completedwork",
            name="saved_org_payment_accrued_usd",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Payment accrued for the workspace in USD.", max_digits=10
            ),
        ),
    ]
