# Generated by Django 4.2.5 on 2026-02-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0113_alter_completedwork_saved_org_payment_accrued_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentinvoice",
            name="invoice_ticket_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
