# Generated by Django 4.2.5 on 2026-03-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0114_paymentinvoice_invoice_ticket_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uservisit",
            name="location",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
