# Generated by Django 4.2.5 on 2026-03-05 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("microplanning", "0002_workarea_case_id"),
        ("opportunity", "0114_paymentinvoice_invoice_ticket_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="uservisit",
            name="work_area",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="microplanning.workarea"
            ),
        ),
    ]
