# Generated by Django 4.2.5 on 2026-03-02 09:34

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pghistory", "0007_auto_20250421_0444"),
        ("opportunity", "0116_remove_task_time_estimate"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpportunityActiveEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="opportunity",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."active" IS DISTINCT FROM (NEW."active"))',
                    func='INSERT INTO "opportunity_opportunityactiveevent" ("active", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."active", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;',
                    hash="45c814c2fb96305b451abfff0f60e4cfb4627d89",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_2d6f3",
                    table="opportunity_opportunity",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="opportunityactiveevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="opportunityactiveevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="active_events",
                to="opportunity.opportunity",
            ),
        ),
    ]
