# Generated by Django 4.2.5 on 2026-03-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0117_task_case_property_and_task_unit_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
