# Generated by Django 4.2.5 on 2026-03-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0117_task_case_property_and_task_unit_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="archived",
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
