# Generated by Django 4.2.5 on 2026-03-25 14:28

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pghistory", "0007_auto_20250421_0444"),
        ("opportunity", "0118_task_archived_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompletedTaskDueDateEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("due_date", models.DateField()),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="completedtask",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."due_date" IS DISTINCT FROM (NEW."due_date"))',
                    func='INSERT INTO "opportunity_completedtaskduedateevent" ("due_date", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."due_date", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;',
                    hash="d47dd3cdf6d5d0156882cb30d753e22a19904a99",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_e3142",
                    table="opportunity_completedtask",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="completedtaskduedateevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="completedtaskduedateevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="due_date_events",
                to="opportunity.completedtask",
            ),
        ),
    ]
