# Generated by Django 4.2.5 on 2026-03-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0119_completedtask_assigned_by_due_date_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="case_property",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="unit_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
