# Generated by Django 4.2.5 on 2026-03-20 16:31

from django.db import migrations, models
import uuid


def populate_assigned_task_id(apps, schema_editor):
    CompletedTask = apps.get_model("opportunity", "CompletedTask")
    for task in CompletedTask.objects.filter(assigned_task_id__isnull=True):
        task.assigned_task_id = uuid.uuid4()
        task.save(update_fields=["assigned_task_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0120_task_case_property_and_task_unit_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="completedtask",
            old_name="date",
            new_name="completed_at",
        ),
        # https://docs.djangoproject.com/en/4.2/howto/writing-migrations/#migrations-that-add-unique-fields
        # Step 1: Add UUID field as nullable, no unique constraint
        migrations.AddField(
            model_name="completedtask",
            name="assigned_task_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        # Step 2: Populate existing rows with unique UUIDs
        migrations.RunPython(populate_assigned_task_id, migrations.RunPython.noop, hints={"run_on_secondary": False}),
        # Step 3: Make non-nullable and add unique constraint
        migrations.AlterField(
            model_name="completedtask",
            name="assigned_task_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
