# Generated by Django 4.2.5 on 2026-03-20 16:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


def populate_task_type_id(apps, schema_editor):
    Task = apps.get_model("opportunity", "Task")
    for task in Task.objects.filter(task_type_id__isnull=True):
        task.task_type_id = uuid.uuid4()
        task.save(update_fields=["task_type_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0121_add_completedtask_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="opportunity",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="opportunity.opportunity"
            ),
        ),
        # https://docs.djangoproject.com/en/4.2/howto/writing-migrations/#migrations-that-add-unique-fields
        # Step 1: Add UUID field as nullable, no unique constraint
        migrations.AddField(
            model_name="task",
            name="task_type_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        # Step 2: Populate existing rows with unique UUIDs
        migrations.RunPython(populate_task_type_id, migrations.RunPython.noop, hints={"run_on_secondary": False}),
        # Step 3: Make non-nullable and add unique constraint
        migrations.AlterField(
            model_name="task",
            name="task_type_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
