# Generated by Django 4.2.5 on 2026-03-26 18:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("opportunity", "0123_task_archived_on"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CompletedTask",
            new_name="AssignedTask",
        ),
    ]
