# Generated by Django 4.2.5 on 2026-04-01 11:17

from django.db import migrations
from django_celery_beat.models import PeriodicTask, CrontabSchedule


def update_periodic_task(apps, schema_editor):
    # Update schedule to run monthly on 2th at 1:00 AM
    schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="00",
        hour="01",
        day_of_week="*",
        day_of_month="2",
        month_of_year="*",
    )
    PeriodicTask.objects.update_or_create(
        name="generate_automated_service_delivery_invoice",
        defaults={
            "task": "commcare_connect.opportunity.tasks.generate_automated_service_delivery_invoice",
            "crontab": schedule,
            "interval": None,
        },
    )



class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0123_task_archived_on"),
    ]

    operations = [
        migrations.RunPython(
            update_periodic_task,
            migrations.RunPython.noop,
            hints={"run_on_secondary": False},
        )
    ]

