# Generated by Django 4.2.5 on 2026-03-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0124_rename_completedtask_assignedtask"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Task",
            new_name="TaskType",
        ),
        migrations.RemoveConstraint(
            model_name="assignedtask",
            name="unique_xform_assigned_task",
        ),
        migrations.RemoveConstraint(
            model_name="tasktype",
            name="unique_task_per_app",
        ),
        migrations.RenameField(
            model_name="assignedtask",
            old_name="task",
            new_name="task_type",
        ),
        migrations.AddConstraint(
            model_name="assignedtask",
            constraint=models.UniqueConstraint(
                fields=("xform_id", "task_type", "opportunity_access"), name="unique_xform_assigned_task"
            ),
        ),
        migrations.AddConstraint(
            model_name="tasktype",
            constraint=models.UniqueConstraint(fields=("app_id", "slug"), name="unique_task_type_per_app"),
        ),
    ]
