# Generated by Django 4.2.5 on 2026-04-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0124_rename_completedtask_assignedtask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignedtask",
            name="completed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="assignedtask",
            name="duration",
            field=models.DurationField(null=True),
        ),
    ]
