# Generated by Django 4.2.5 on 2026-03-26 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("opportunity", "0124_rename_completedtask_assignedtask"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="assignedtask",
            name="unique_xform_completed_task",
        ),
        migrations.AlterField(
            model_name="assignedtask",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="assignedtask",
            constraint=models.UniqueConstraint(
                fields=("xform_id", "task", "opportunity_access"), name="unique_xform_assigned_task"
            ),
        ),
    ]
