# Generated by Django 4.2.5 on 2026-04-01 13:53

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0125_completedtaskduedateevent_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="assignedtask",
            name="update_update",
        ),
        migrations.AlterField(
            model_name="assignedtask",
            name="completed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="assignedtask",
            name="duration",
            field=models.DurationField(null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="assignedtask",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."due_date" IS DISTINCT FROM (NEW."due_date"))',
                    func='INSERT INTO "opportunity_assignedtaskduedateevent" ("due_date", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."due_date", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;',
                    hash="ed9ad7ca6af4e59a52ded42bd6a10e50f47a537d",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_5fe6b",
                    table="opportunity_assignedtask",
                    when="AFTER",
                ),
            ),
        ),
    ]
