# Generated by Django 4.2.5 on 2026-05-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0128_remove_assignedtask_update_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='automatic_verification',
            field=models.BooleanField(default=False),
        ),
    ]
