# Generated by Django 4.2.5 on 2026-05-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0128_remove_assignedtask_update_update_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasktype",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
