# Generated by Django 4.2.5 on 2026-05-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0129_alter_tasktype_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="automatic_visit_verification",
            field=models.BooleanField(default=False),
        ),
    ]
