# Generated by Django 4.2.5 on 2026-05-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0130_opportunity_automatic_visit_verification"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="assignedtask",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "assigned")),
                fields=("task_type", "opportunity_access"),
                name="unique_assigned_task_type_per_access",
            ),
        ),
    ]
