# Generated by Django 4.2.5 on 2026-06-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0131_add_unique_assigned_task_type_per_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunityverificationflags",
            name="duplicate",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="opportunityverificationflags",
            name="gps",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="opportunityverificationflags",
            name="location",
            field=models.PositiveIntegerField(verbose_name=0),
        ),
    ]
