# Generated by Django 4.2.30 on 2026-06-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunity", "0132_alter_opportunityverificationflags_duplicate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunityverificationflags",
            name="location",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
