# Generated by Django 4.2.5 on 2025-04-18 10:22

from django.db import migrations
from django_celery_beat.models import PeriodicTask


def delete_cache_report_task(apps, schema_editor):
    PeriodicTask.objects.get(
        name="prime_report_cache",
        task="commcare_connect.reports.tasks.prime_report_cache",
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [migrations.RunPython(delete_cache_report_task, migrations.RunPython.noop)]
