# Generated by Django 4.2.5 on 2025-11-21 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0002_remove_prime_report_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAnalyticsData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(unique=True)),
                ("has_opp_invite", models.DateTimeField(null=True)),
                ("has_ever_earned_payment", models.DateTimeField(null=True)),
                ("has_started_learning", models.DateTimeField(null=True)),
                ("has_completed_learning", models.DateTimeField(null=True)),
                ("has_completed_assessment", models.DateTimeField(null=True)),
                ("has_claimed_job", models.DateTimeField(null=True)),
                ("has_started_job", models.DateTimeField(null=True)),
                ("has_paid", models.DateTimeField(null=True)),
                ("has_completed_opp", models.DateTimeField(null=True)),
                ("has_completed_multiple_opps", models.DateTimeField(null=True)),
                ("has_offered_multiple_opps", models.DateTimeField(null=True)),
                ("has_accepted_multiple_opps", models.DateTimeField(null=True)),
                ("has_sso_on_hq_app", models.DateTimeField(null=True)),
                (
                    "user",
                    models.OneToOneField(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
