# Generated by Django 4.2.5 on 2025-12-05 09:39

from django.db import migrations
from django_celery_beat.models import CrontabSchedule, PeriodicTask


def create_user_analytics_syncing_task(apps, schema_editor):
    schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="00",
        hour="01",
        day_of_week="*",
        day_of_month="*",
        month_of_year="*",
    )
    PeriodicTask.objects.update_or_create(
        crontab=schedule,
        name="prime_report_cache",
        task="commcare_connect.reports.tasks.update_user_analytics_data",
    )


def delete_user_analytics_syncing_task(apps, schema_editor):
    PeriodicTask.objects.get(
        name="prime_report_cache",
        task="commcare_connect.reports.tasks.update_user_analytics_data",
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0003_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_user_analytics_syncing_task, delete_user_analytics_syncing_task, hints={"run_on_secondary": False}
        )
    ]
