# Generated by Django 4.2.5 on 2026-02-16 12:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("opportunity", "0109_paymentunit_org_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkAreaGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ward", models.SlugField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                (
                    "assigned_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="opportunity.opportunityaccess",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="opportunity.opportunity"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkArea",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique identifier for the Work Area within an Opportunity. Automatically generated slugs must be unique per opportunity.",
                        max_length=255,
                    ),
                ),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Centroid of the Work Area as a Point. Use (longitude, latitude) when assigning manually.",
                        srid=4326,
                    ),
                ),
                ("boundary", django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ("ward", models.SlugField(max_length=255)),
                ("building_count", models.PositiveIntegerField(default=0)),
                ("expected_visit_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("UNASSIGNED", "Unassigned"),
                            ("NOT_VISITED", "Not Visited"),
                            ("VISITED", "Visited"),
                            ("REQUEST_FOR_INACCESSIBLE", "Request for Inaccessible"),
                            ("EXPECTED_VISIT_REACHED", "Expected Visit Count Reached"),
                            ("INACCESSIBLE", "Inaccessible"),
                            ("EXCLUDED", "Excluded"),
                        ],
                        default="NOT_STARTED",
                        max_length=50,
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="opportunity.opportunity"),
                ),
                (
                    "work_area_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="microplanning.workareagroup",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="workareagroup",
            constraint=models.UniqueConstraint(fields=("name", "opportunity"), name="unique_name_per_opportunity"),
        ),
        migrations.AddConstraint(
            model_name="workarea",
            constraint=models.UniqueConstraint(fields=("slug", "opportunity"), name="unique_slug_per_opportunity"),
        ),
    ]
