# Generated by Django 4.2.5 on 2026-02-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("microplanning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workarea",
            name="case_id",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
