# Generated by Django 4.2.5 on 2026-03-18 09:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("microplanning", "0002_workarea_case_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workareagroup",
            old_name="assigned_user",
            new_name="opportunity_access",
        ),
    ]
