# Generated by Django 4.2.5 on 2026-03-13 08:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("microplanning", "0002_workarea_case_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="workareagroup",
            name="boundary",
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name="workareagroup",
            name="building_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
