# Generated by Django 4.2.5 on 2026-03-19 13:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("microplanning", "0003_rename_assigned_user_workareagroup_opportunity_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="workareagroup",
            name="boundary",
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
