# Generated by Django 4.2.5 on 2026-03-19 07:16

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pghistory", "0007_auto_20250421_0444"),
        ("microplanning", "0003_rename_assigned_user_workareagroup_opportunity_access"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkAreaExpectedVisitCountWorkAreaGroupEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("expected_visit_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="workarea",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "microplanning_workareaexpectedvisitcountworkareagroupevent" ("expected_visit_count", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "work_area_group_id") VALUES (NEW."expected_visit_count", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."work_area_group_id"); RETURN NULL;',
                    hash="2a9cdf0664d8aeff586aec8a4047fa2910f37c24",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_20a25",
                    table="microplanning_workarea",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="workarea",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."expected_visit_count" IS DISTINCT FROM (NEW."expected_visit_count") OR OLD."work_area_group_id" IS DISTINCT FROM (NEW."work_area_group_id"))',
                    func='INSERT INTO "microplanning_workareaexpectedvisitcountworkareagroupevent" ("expected_visit_count", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "work_area_group_id") VALUES (NEW."expected_visit_count", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."work_area_group_id"); RETURN NULL;',
                    hash="6be13fddf19fcfd892e393159c99893e8439a41e",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_c5fd6",
                    table="microplanning_workarea",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="workareaexpectedvisitcountworkareagroupevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="workareaexpectedvisitcountworkareagroupevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="expected_visit_count_work_area_group_events",
                to="microplanning.workarea",
            ),
        ),
        migrations.AddField(
            model_name="workareaexpectedvisitcountworkareagroupevent",
            name="work_area_group",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="microplanning.workareagroup",
            ),
        ),
    ]
