# Generated by Django 4.2.5 on 2026-03-23 05:20

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("microplanning", "0004_workareaexpectedvisitcountworkareagroupevent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workareagroup",
            name="boundary",
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
