# Generated by Django 4.2.5 on 2026-04-29 16:54

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pghistory", "0007_auto_20250421_0444"),
        ("microplanning", "0004_workareaexpectedvisitcountworkareagroupevent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkAreaExpectedVisitCountWorkAreaGroupStatusEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("expected_visit_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("UNASSIGNED", "Unassigned"),
                            ("NOT_VISITED", "Not Visited"),
                            ("VISITED", "Visited"),
                            ("REQUEST_FOR_INACCESSIBLE", "Request for Inaccessible"),
                            ("EXPECTED_VISIT_REACHED", "Expected Visit Count Reached"),
                            ("INACCESSIBLE", "Inaccessible"),
                            ("EXCLUDED", "Excluded"),
                        ],
                        default="UNASSIGNED",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="workareaexpectedvisitcountworkareagroupevent",
            name="pgh_context",
        ),
        migrations.RemoveField(
            model_name="workareaexpectedvisitcountworkareagroupevent",
            name="pgh_obj",
        ),
        migrations.RemoveField(
            model_name="workareaexpectedvisitcountworkareagroupevent",
            name="work_area_group",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="workarea",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="workarea",
            name="update_update",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="workarea",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "microplanning_workareaexpectedvisitcountworkareagroupstatuscadb" ("expected_visit_count", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "work_area_group_id") VALUES (NEW."expected_visit_count", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status", NEW."work_area_group_id"); RETURN NULL;',
                    hash="631b25b9b3c674810b956295d492063e094b23c7",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_20a25",
                    table="microplanning_workarea",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="workarea",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."expected_visit_count" IS DISTINCT FROM (NEW."expected_visit_count") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."work_area_group_id" IS DISTINCT FROM (NEW."work_area_group_id"))',
                    func='INSERT INTO "microplanning_workareaexpectedvisitcountworkareagroupstatuscadb" ("expected_visit_count", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "work_area_group_id") VALUES (NEW."expected_visit_count", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status", NEW."work_area_group_id"); RETURN NULL;',
                    hash="e0f6c2d933686c6cab133d1bb369cc1bf9f163ee",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_c5fd6",
                    table="microplanning_workarea",
                    when="AFTER",
                ),
            ),
        ),
        migrations.DeleteModel(
            name="WorkAreaExpectedVisitCountWorkAreaGroupEvent",
        ),
        migrations.AddField(
            model_name="workareaexpectedvisitcountworkareagroupstatusevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="workareaexpectedvisitcountworkareagroupstatusevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="expected_visit_count_work_area_group_status_events",
                to="microplanning.workarea",
            ),
        ),
        migrations.AddField(
            model_name="workareaexpectedvisitcountworkareagroupstatusevent",
            name="work_area_group",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="microplanning.workareagroup",
            ),
        ),
    ]
