# Generated by Django 4.2.5 on 2026-05-05 11:02

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


def copy_opportunity_access_from_group_to_work_areas(apps, schema_editor):
    WorkArea = apps.get_model("microplanning", "WorkArea")
    WorkAreaGroup = apps.get_model("microplanning", "WorkAreaGroup")
    for group in WorkAreaGroup.objects.filter(opportunity_access__isnull=False).iterator():
        WorkArea.objects.filter(
            work_area_group=group,
            opportunity_access__isnull=True,
        ).update(opportunity_access=group.opportunity_access)


class Migration(migrations.Migration):
    dependencies = [
        ("pghistory", "0007_auto_20250421_0444"),
        ("opportunity", "0128_remove_assignedtask_update_update_and_more"),
        ("microplanning", "0005_workareaexpectedvisitcountworkareagroupstatusevent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkAreaExpectedVisitCountWorkAreaGroupStatusOpportunityAccessEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("expected_visit_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("UNASSIGNED", "Unassigned"),
                            ("NOT_VISITED", "Not Visited"),
                            ("VISITED", "Visited"),
                            ("REQUEST_FOR_INACCESSIBLE", "Request for Inaccessible"),
                            ("EXPECTED_VISIT_REACHED", "Expected Visit Count Reached"),
                            ("INACCESSIBLE", "Inaccessible"),
                            ("EXCLUDED", "Excluded"),
                        ],
                        default="UNASSIGNED",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="workareaexpectedvisitcountworkareagroupstatusevent",
            name="pgh_context",
        ),
        migrations.RemoveField(
            model_name="workareaexpectedvisitcountworkareagroupstatusevent",
            name="pgh_obj",
        ),
        migrations.RemoveField(
            model_name="workareaexpectedvisitcountworkareagroupstatusevent",
            name="work_area_group",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="workarea",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="workarea",
            name="update_update",
        ),
        migrations.AddField(
            model_name="workarea",
            name="opportunity_access",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="opportunity.opportunityaccess"
            ),
        ),
        migrations.RunPython(
            copy_opportunity_access_from_group_to_work_areas,
            reverse_code=migrations.RunPython.noop,
            hints={"run_on_secondary": False},
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="workarea",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "microplanning_workareaexpectedvisitcountworkareagroupstatus3249" ("expected_visit_count", "opportunity_access_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "work_area_group_id") VALUES (NEW."expected_visit_count", NEW."opportunity_access_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status", NEW."work_area_group_id"); RETURN NULL;',
                    hash="e1c5a7a013c5c83ea5bb9f26249e8382260bb442",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_20a25",
                    table="microplanning_workarea",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="workarea",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."expected_visit_count" IS DISTINCT FROM (NEW."expected_visit_count") OR OLD."opportunity_access_id" IS DISTINCT FROM (NEW."opportunity_access_id") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."work_area_group_id" IS DISTINCT FROM (NEW."work_area_group_id"))',
                    func='INSERT INTO "microplanning_workareaexpectedvisitcountworkareagroupstatus3249" ("expected_visit_count", "opportunity_access_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "work_area_group_id") VALUES (NEW."expected_visit_count", NEW."opportunity_access_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status", NEW."work_area_group_id"); RETURN NULL;',
                    hash="6c18e113d61a14ff8637eaef4777c1be8b57cad7",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_c5fd6",
                    table="microplanning_workarea",
                    when="AFTER",
                ),
            ),
        ),
        migrations.DeleteModel(
            name="WorkAreaExpectedVisitCountWorkAreaGroupStatusEvent",
        ),
        migrations.AddField(
            model_name="workareaexpectedvisitcountworkareagroupstatusopportunityaccessevent",
            name="opportunity_access",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="opportunity.opportunityaccess",
            ),
        ),
        migrations.AddField(
            model_name="workareaexpectedvisitcountworkareagroupstatusopportunityaccessevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="workareaexpectedvisitcountworkareagroupstatusopportunityaccessevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="expected_visit_count_work_area_group_status_opportunity_access_events",
                to="microplanning.workarea",
            ),
        ),
        migrations.AddField(
            model_name="workareaexpectedvisitcountworkareagroupstatusopportunityaccessevent",
            name="work_area_group",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="microplanning.workareagroup",
            ),
        ),
    ]
