# Generated by Django 4.2.5 on 2026-05-05 11:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("microplanning", "0006_workareaexpectedvisitcountworkareagroupstatusopportunityaccessevent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workareagroup",
            name="opportunity_access",
        ),
    ]
