# Generated by Django 4.2.5 on 2026-05-06 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("opportunity", "0128_remove_assignedtask_update_update_and_more"),
        ("pghistory", "0007_auto_20250421_0444"),
        ("microplanning", "0007_remove_workareagroup_opportunity_access"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkAreaExpectedVisitCountWorkAreaGroupStatusOpportunityAccessExcludedReasonEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("expected_visit_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("UNASSIGNED", "Unassigned"),
                            ("NOT_VISITED", "Not Visited"),
                            ("VISITED", "Visited"),
                            ("REQUEST_FOR_INACCESSIBLE", "Request for Inaccessible"),
                            ("EXPECTED_VISIT_REACHED", "Expected Visit Count Reached"),
                            ("INACCESSIBLE", "Inaccessible"),
                            ("EXCLUDED", "Excluded"),
                        ],
                        default="UNASSIGNED",
                        max_length=50,
                    ),
                ),
                ("excluded_reason", models.CharField(blank=True, default="", max_length=500)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="workareaexpectedvisitcountworkareagroupstatusopportunityaccessevent",
            name="opportunity_access",
        ),
        migrations.RemoveField(
            model_name="workareaexpectedvisitcountworkareagroupstatusopportunityaccessevent",
            name="pgh_context",
        ),
        migrations.RemoveField(
            model_name="workareaexpectedvisitcountworkareagroupstatusopportunityaccessevent",
            name="pgh_obj",
        ),
        migrations.RemoveField(
            model_name="workareaexpectedvisitcountworkareagroupstatusopportunityaccessevent",
            name="work_area_group",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="workarea",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="workarea",
            name="update_update",
        ),
        migrations.AddField(
            model_name="workarea",
            name="excluded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="excluded_work_areas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workarea",
            name="excluded_reason",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="workarea",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "microplanning_workareaexpectedvisitcountworkareagroupstatus0ff4" ("excluded_reason", "expected_visit_count", "opportunity_access_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "work_area_group_id") VALUES (NEW."excluded_reason", NEW."expected_visit_count", NEW."opportunity_access_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status", NEW."work_area_group_id"); RETURN NULL;',
                    hash="d888ec67950bf1b625cf09e0b609a553a44dfd15",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_20a25",
                    table="microplanning_workarea",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="workarea",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."excluded_reason" IS DISTINCT FROM (NEW."excluded_reason") OR OLD."expected_visit_count" IS DISTINCT FROM (NEW."expected_visit_count") OR OLD."opportunity_access_id" IS DISTINCT FROM (NEW."opportunity_access_id") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."work_area_group_id" IS DISTINCT FROM (NEW."work_area_group_id"))',
                    func='INSERT INTO "microplanning_workareaexpectedvisitcountworkareagroupstatus0ff4" ("excluded_reason", "expected_visit_count", "opportunity_access_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "work_area_group_id") VALUES (NEW."excluded_reason", NEW."expected_visit_count", NEW."opportunity_access_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status", NEW."work_area_group_id"); RETURN NULL;',
                    hash="024b0366836d58d9f11ff6bc2b1a0a5f8872ab63",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_c5fd6",
                    table="microplanning_workarea",
                    when="AFTER",
                ),
            ),
        ),
        migrations.DeleteModel(
            name="WorkAreaExpectedVisitCountWorkAreaGroupStatusOpportunityAccessEvent",
        ),
        migrations.AddField(
            model_name="workareaexpectedvisitcountworkareagroupstatusopportunityaccessexcludedreasonevent",
            name="opportunity_access",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="opportunity.opportunityaccess",
            ),
        ),
        migrations.AddField(
            model_name="workareaexpectedvisitcountworkareagroupstatusopportunityaccessexcludedreasonevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="workareaexpectedvisitcountworkareagroupstatusopportunityaccessexcludedreasonevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="expected_visit_count_work_area_group_status_opportunity_access_excluded_reason_events",
                to="microplanning.workarea",
            ),
        ),
        migrations.AddField(
            model_name="workareaexpectedvisitcountworkareagroupstatusopportunityaccessexcludedreasonevent",
            name="work_area_group",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="microplanning.workareagroup",
            ),
        ),
    ]
