# Generated by Django 4.2.5 on 2026-05-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "microplanning",
            "0008_workareaexpectedvisitcountworkareagroupstatusopportunityaccessexcludedreasonevent_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="workarea",
            name="target_population",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
