# Generated by Django 4.2.5 on 2026-05-04 07:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0128_remove_assignedtask_update_update_and_more"),
        ("microplanning", "0009_add_target_population_to_work_area"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkAreaInaccessibilityRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("xform_id", models.CharField(max_length=50)),
                ("date_of_visit", models.DateField()),
                ("location", django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ("reason", models.CharField(max_length=256)),
                ("additional_details", models.TextField(blank=True, default="")),
                (
                    "opportunity_access",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="opportunity.opportunityaccess"),
                ),
                (
                    "work_area",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="microplanning.workarea"),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="workareainaccessibilityrequest",
            constraint=models.UniqueConstraint(
                fields=("xform_id", "work_area"), name="unique_xform_work_area_inaccessibility"
            ),
        ),
    ]
