# Generated by Django 4.2.5 on 2026-05-28 05:40

from django.db import migrations, models


def migrate_not_started_to_not_visited(apps, schema_editor):
    WorkArea = apps.get_model("microplanning", "WorkArea")
    WorkArea.objects.filter(status="NOT_STARTED").update(status="NOT_VISITED")


class Migration(migrations.Migration):
    dependencies = [
        ("microplanning", "0010_workareainaccessibilityrequest_and_more"),
    ]

    operations = [
        migrations.RunPython(
            migrate_not_started_to_not_visited,
            migrations.RunPython.noop,
            hints={"run_on_secondary": False},
        ),
        migrations.AlterField(
            model_name="workarea",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNASSIGNED", "Unassigned"),
                    ("NOT_VISITED", "Not Visited"),
                    ("VISITED", "Visited"),
                    ("REQUEST_FOR_INACCESSIBLE", "Request for Inaccessible"),
                    ("EXPECTED_VISIT_REACHED", "Expected Visit Count Reached"),
                    ("INACCESSIBLE", "Inaccessible"),
                    ("EXCLUDED", "Excluded"),
                ],
                default="UNASSIGNED",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="workareaexpectedvisitcountworkareagroupstatusopportunityaccessexcludedreasonevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNASSIGNED", "Unassigned"),
                    ("NOT_VISITED", "Not Visited"),
                    ("VISITED", "Visited"),
                    ("REQUEST_FOR_INACCESSIBLE", "Request for Inaccessible"),
                    ("EXPECTED_VISIT_REACHED", "Expected Visit Count Reached"),
                    ("INACCESSIBLE", "Inaccessible"),
                    ("EXCLUDED", "Excluded"),
                ],
                default="UNASSIGNED",
                max_length=50,
            ),
        ),
    ]
