# Generated by Django 4.2.5 on 2026-05-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("microplanning", "0011_alter_workarea_status_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="workareainaccessibilityrequest",
            name="unique_xform_work_area_inaccessibility",
        ),
        migrations.AddConstraint(
            model_name="workareainaccessibilityrequest",
            constraint=models.UniqueConstraint(fields=("work_area",), name="unique_work_area_inaccessibility"),
        ),
    ]
