# Generated by Django 4.2.5 on 2026-05-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "microplanning",
            "0012_remove_workareainaccessibilityrequest_unique_xform_work_area_inaccessibility_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="workarea",
            name="case_id",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
