# Generated by Django 4.2.5 on 2026-06-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("microplanning", "0013_alter_workarea_case_id"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="workareaexpectedvisitcountworkareagroupstatusopportunityaccessexcludedreasonevent",
            index=models.Index(fields=["pgh_obj", "status", "pgh_created_at"], name="wae_obj_status_created_idx"),
        ),
    ]
