# Generated by Django 4.2.5 on 2025-11-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentrecord',
            name='opportunity',
        ),
        migrations.RemoveField(
            model_name='experimentrecord',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='experimentrecord',
            name='program',
        ),
        migrations.RemoveField(
            model_name='experimentrecord',
            name='user',
        ),
        migrations.AddField(
            model_name='experimentrecord',
            name='opportunity_id',
            field=models.IntegerField(blank=True, help_text='Production opportunity ID', null=True),
        ),
        migrations.AddField(
            model_name='experimentrecord',
            name='organization_id',
            field=models.IntegerField(blank=True, help_text='Production organization ID', null=True),
        ),
        migrations.AddField(
            model_name='experimentrecord',
            name='program_id',
            field=models.IntegerField(blank=True, help_text='Production program ID', null=True),
        ),
        migrations.AddField(
            model_name='experimentrecord',
            name='user_id',
            field=models.IntegerField(blank=True, help_text='Production user ID', null=True),
        ),
        migrations.AddIndex(
            model_name='experimentrecord',
            index=models.Index(fields=['program_id'], name='labs_experi_program_559e93_idx'),
        ),
        migrations.AddIndex(
            model_name='experimentrecord',
            index=models.Index(fields=['organization_id'], name='labs_experi_organiz_1f01ed_idx'),
        ),
    ]
