# Generated by Django 4.2.5 on 2025-11-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_remove_experimentrecord_opportunity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentrecord',
            name='organization_id',
            field=models.CharField(blank=True, help_text='Production organization slug or ID', max_length=255, null=True),
        ),
    ]
