# Generated by Django 4.2.5 on 2025-12-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("labs", "0004_remove_experiment_record"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawVisitCache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("opportunity_id", models.IntegerField(db_index=True)),
                ("visit_count", models.IntegerField(help_text="Visit count when cached, for invalidation")),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("visit_id", models.IntegerField(db_index=True, help_text="Original visit ID from Connect")),
                ("username", models.CharField(db_index=True, max_length=255)),
                ("deliver_unit", models.CharField(blank=True, max_length=500)),
                ("deliver_unit_id", models.IntegerField(blank=True, null=True)),
                ("entity_id", models.CharField(blank=True, max_length=255)),
                ("entity_name", models.CharField(blank=True, max_length=500)),
                ("visit_date", models.DateField(blank=True, db_index=True, null=True)),
                ("status", models.CharField(blank=True, db_index=True, max_length=50)),
                ("reason", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("flagged", models.BooleanField(default=False)),
                ("flag_reason", models.JSONField(blank=True, default=dict)),
                ("form_json", models.JSONField(blank=True, default=dict)),
                ("completed_work", models.JSONField(blank=True, default=dict)),
                ("status_modified_date", models.DateTimeField(blank=True, null=True)),
                ("review_status", models.CharField(blank=True, max_length=50)),
                ("review_created_on", models.DateTimeField(blank=True, null=True)),
                ("justification", models.TextField(blank=True)),
                ("date_created", models.DateTimeField(blank=True, null=True)),
                ("completed_work_id", models.IntegerField(blank=True, null=True)),
                ("images", models.JSONField(blank=True, default=list)),
            ],
            options={
                "db_table": "labs_raw_visit_cache",
                "indexes": [
                    models.Index(fields=["opportunity_id", "visit_count"], name="labs_raw_vi_opportu_91eff4_idx"),
                    models.Index(fields=["opportunity_id", "username"], name="labs_raw_vi_opportu_88da61_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ComputedVisitCache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("opportunity_id", models.IntegerField(db_index=True)),
                ("config_hash", models.CharField(db_index=True, help_text="Hash of analysis config", max_length=32)),
                ("visit_count", models.IntegerField(help_text="Visit count when cached, for invalidation")),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("visit_id", models.IntegerField(db_index=True)),
                ("username", models.CharField(db_index=True, max_length=255)),
                ("computed_fields", models.JSONField(default=dict, help_text="Computed field values from config")),
            ],
            options={
                "db_table": "labs_computed_visit_cache",
                "indexes": [
                    models.Index(
                        fields=["opportunity_id", "config_hash", "visit_count"], name="labs_comput_opportu_ef588d_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ComputedFLWCache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("opportunity_id", models.IntegerField(db_index=True)),
                ("config_hash", models.CharField(db_index=True, help_text="Hash of analysis config", max_length=32)),
                ("visit_count", models.IntegerField(help_text="Visit count when cached, for invalidation")),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("username", models.CharField(db_index=True, max_length=255)),
                ("aggregated_fields", models.JSONField(default=dict, help_text="Aggregated field values")),
                ("total_visits", models.IntegerField(default=0)),
                ("approved_visits", models.IntegerField(default=0)),
                ("pending_visits", models.IntegerField(default=0)),
                ("rejected_visits", models.IntegerField(default=0)),
                ("flagged_visits", models.IntegerField(default=0)),
                ("first_visit_date", models.DateField(blank=True, null=True)),
                ("last_visit_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "labs_computed_flw_cache",
                "indexes": [
                    models.Index(
                        fields=["opportunity_id", "config_hash", "visit_count"], name="labs_comput_opportu_4919d4_idx"
                    )
                ],
            },
        ),
    ]
