# Generated by Django 4.2.5 on 2025-12-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labs", "0005_sql_cache_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="computedvisitcache",
            name="deliver_unit",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="computedvisitcache",
            name="deliver_unit_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="computedvisitcache",
            name="entity_id",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="computedvisitcache",
            name="entity_name",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="computedvisitcache",
            name="flagged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="computedvisitcache",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="computedvisitcache",
            name="status",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="computedvisitcache",
            name="visit_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
