# Generated by Django 4.2.5 on 2025-12-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labs", "0006_add_base_fields_to_computed_visit_cache"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computedvisitcache",
            name="deliver_unit",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="computedvisitcache",
            name="entity_id",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="computedvisitcache",
            name="entity_name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="computedvisitcache",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="computedvisitcache",
            name="status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
