# Generated by Django 4.2.5 on 2026-02-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labs", "0007_allow_null_base_fields_computed_visit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computedvisitcache",
            name="visit_id",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="rawvisitcache",
            name="visit_id",
            field=models.CharField(
                db_index=True, help_text="Visit ID (numeric for Connect, UUID for CCHQ)", max_length=255
            ),
        ),
    ]
